<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Does item format impact response?</title>

<script src="site_libs/header-attrs-2.8/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">On item wording effects</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="1-cleaning.html">Data cleaning</a>
</li>
<li>
  <a href="descriptives.html">Descriptives</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Analysis
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="analysis_format.html">Does item formatting affect response?</a>
    </li>
    <li>
      <a href="internal.html">Does item formatting affect internal consistency?</a>
    </li>
    <li>
      <a href="test_retest.html">Does item formatting affect test-retest reliability?</a>
    </li>
    <li>
      <a href="timing_format.html">Does timing differ across format?</a>
    </li>
    <li>
      <a href="device.html">Does device type affect response and timing?</a>
    </li>
  </ul>
</li>
<li>
  <a href="power.html">Power analysis</a>
</li>
<li>
  <a href="workspace.html">R version and packages</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/pie-lab/wording-effects">
    <span class="fas fa-github"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Does item format impact response?</h1>
<h4 class="date">Last updated 2021-08-19</h4>

</div>


<p>The primary aims of this study are to evaluate the effects of item wording in online, self-report personality assessment. Specifically, we intend to consider the extent to which incremental wording changes may influence differences in the distributions of responses, response times, and psychometric properties of the items. These wording changes will include a progression from using (1) trait-descriptive adjectives by themselves, (2) with the linking verb “to be” (Am…), (3) with the additional verb “to tend” (Tend to be…), and (4) with the pronoun “someone” (Am someone who tends to be…).</p>
<p>Using a protocol that administers each adjective twice to the same participant (in different combinations of item format administered randomly across participants), we will use between-person analyses to compare responses using group-level data for the different formats.</p>
<p>These analyses will attempt to account for delayed_memory effects by collecting data on immediate and delayed recall (5 minutes and approximately two weeks) using a delayed_memory paradigm that was developed based on a similar recall task used in the HRS (Runge et al., 2015).</p>
<div id="effect-of-format-block-1-data" class="section level2">
<h2>Effect of format (Block 1 data)</h2>
<p>We used a multilevel model, nesting response within participant to account for dependence. Our primary predictor was format. Here, we use only Block 1 data; in other words, effects are largely between person, although each person contributes 31 unique data points to the analysis (one for each trait). We use the <code>anova</code> function to estimate the amount of variability in response due to format.</p>
<pre class="r"><code>item_block1 = filter(items_df, block == &quot;1&quot;)

mod.format_b1 = lmer(response~format + (1|proid), 
                  data = item_block1)
anova(mod.format_b1)</code></pre>
<pre><code>## Type III Analysis of Variance Table with Satterthwaite&#39;s method
##        Sum Sq Mean Sq NumDF DenDF F value Pr(&gt;F)
## format 1.3559 0.45198     3    31  0.3033 0.8228</code></pre>
<p>When examining only Block 1 data, item format was unassociated with participants’ responses to personality items <span class="math inline">\((F(3, 31.00) = 0.30, p = .823)\)</span>.</p>
<pre class="r"><code>plot_b1 = plot_model(mod.format_b1, type = &quot;pred&quot;)

plot_b1$format +
  labs(x = NULL,
       y = &quot;Average response&quot;,
       title = &quot;Average responses by item formatting (Block 1 Data)&quot;) +
  theme_pubclean()</code></pre>
<div class="figure">
<img src="analysis_format_files/figure-html/analysis-format-7-1.png" alt="Predicted response on personality items by condition, using only Block 1 data." width="672" />
<p class="caption">
Predicted response on personality items by condition, using only Block 1 data.
</p>
</div>
<pre class="r"><code>means_by_group = item_block1 %&gt;%
  group_by(format) %&gt;%
  summarise(m = mean(response),
            s = sd(response))

item_block1 %&gt;%
  ggplot(aes(x = response, fill = format)) +
  geom_histogram(bins = 6, color = &quot;white&quot;) +
  geom_vline(aes(xintercept = m), data = means_by_group) +
  geom_text(aes(x = 1,
                y = 125,
                label = paste(&quot;M =&quot;, round(m,2),
                              &quot;\nSD =&quot;, round(s,2))),
            data = means_by_group,
            hjust =0,
            vjust = 1) +
  facet_wrap(~format) +
  guides(fill = &quot;none&quot;) +
  scale_x_continuous(breaks = 1:6) +
  labs(y = &quot;Number of particpants&quot;,
       title = &quot;Distribution of responses by format (Block 1 data)&quot;) +
  theme_pubr()</code></pre>
<div class="figure">
<img src="analysis_format_files/figure-html/analysis-format-8-1.png" alt="Distribution of responses by category, block 1 data only" width="672" />
<p class="caption">
Distribution of responses by category, block 1 data only
</p>
</div>
<div id="one-model-for-each-adjective" class="section level3">
<h3>One model for each adjective</h3>
<p>We repeat this analysis separately for each trait. Because there is only one response per participant (when using only Block 1 data), we can drop the use of multilevel models and instead rely on a simple general linear model to test our hypothesis. Sepecfically, we test whether the proportion of variance attributable to item format is statistically significant.</p>
<pre class="r"><code>mod_by_item_b1 = item_block1 %&gt;%
  group_by(item) %&gt;%
  nest() %&gt;%
  mutate(mod = map(data, ~lm(response~format, data = .))) %&gt;%
  mutate(aov = map(mod, anova))</code></pre>
<p>We apply a Holm correction to the <em>p</em>-values extracted from these analyses, to adjust for the number of tests conducted. We present results in a table, which is organized by whether items were reverse-coded prior to analysis.</p>
<pre class="r"><code>summary_by_item_b1 = mod_by_item_b1 %&gt;%
  ungroup() %&gt;%
  mutate(tidy = map(aov, broom::tidy)) %&gt;%
  select(item, tidy) %&gt;%
  unnest(cols = c(tidy)) %&gt;%
  filter(term == &quot;format&quot;) %&gt;%
  mutate(reverse = case_when(
    item %in% reverse ~ &quot;Y&quot;,
    TRUE ~ &quot;N&quot;
  )) %&gt;%
  mutate(p.adj = p.adjust(p.value, method = &quot;holm&quot;))

summary_by_item_b1 %&gt;%
  mutate(across( starts_with(&quot;p&quot;), printp )) %&gt;% # format p-values
  arrange(reverse, item) %&gt;%
  select(item, reverse, sumsq, meansq, df, statistic, p.value, p.adj) %&gt;%
  kable(digits = 2,
        booktabs = T,
        col.names = c(&quot;Item&quot;, &quot;Reverse\nScored?&quot;, &quot;SS&quot;, &quot;MS&quot;, &quot;df&quot;, &quot;F&quot;, &quot;raw&quot;, &quot;adj&quot;),
        caption = &quot;Format effects on response by item (block 1 data only)&quot;) %&gt;%
  kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
Format effects on response by item (block 1 data only)
</caption>
<thead>
<tr>
<th style="text-align:left;">
Item
</th>
<th style="text-align:left;">
Reverse Scored?
</th>
<th style="text-align:right;">
SS
</th>
<th style="text-align:right;">
MS
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:right;">
F
</th>
<th style="text-align:left;">
raw
</th>
<th style="text-align:left;">
adj
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
active
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
2.80
</td>
<td style="text-align:right;">
0.93
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.61
</td>
<td style="text-align:left;">
.611
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
adventurous
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.34
</td>
<td style="text-align:right;">
0.45
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.50
</td>
<td style="text-align:left;">
.682
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
broadminded
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
2.27
</td>
<td style="text-align:right;">
0.76
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.66
</td>
<td style="text-align:left;">
.581
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
calm
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
3.77
</td>
<td style="text-align:right;">
1.26
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1.29
</td>
<td style="text-align:left;">
.295
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
caring
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
2.47
</td>
<td style="text-align:right;">
0.82
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1.17
</td>
<td style="text-align:left;">
.337
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
cautious
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.55
</td>
<td style="text-align:right;">
0.52
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.32
</td>
<td style="text-align:left;">
.814
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
creative
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
2.35
</td>
<td style="text-align:right;">
0.78
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.79
</td>
<td style="text-align:left;">
.507
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
curious
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.52
</td>
<td style="text-align:right;">
0.17
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.15
</td>
<td style="text-align:left;">
.927
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
friendly
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.52
</td>
<td style="text-align:right;">
0.17
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.34
</td>
<td style="text-align:left;">
.796
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
hardworking
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.03
</td>
<td style="text-align:right;">
0.01
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.02
</td>
<td style="text-align:left;">
.997
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
helpful
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.20
</td>
<td style="text-align:right;">
0.07
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.08
</td>
<td style="text-align:left;">
.968
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
imaginative
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.40
</td>
<td style="text-align:right;">
0.47
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.58
</td>
<td style="text-align:left;">
.630
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
intelligent
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.86
</td>
<td style="text-align:right;">
0.62
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.44
</td>
<td style="text-align:left;">
.725
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
lively
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.15
</td>
<td style="text-align:right;">
0.38
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.36
</td>
<td style="text-align:left;">
.782
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
organized
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
2.20
</td>
<td style="text-align:right;">
0.73
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.66
</td>
<td style="text-align:left;">
.583
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
outgoing
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.58
</td>
<td style="text-align:right;">
0.53
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.40
</td>
<td style="text-align:left;">
.755
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
responsible
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.87
</td>
<td style="text-align:right;">
0.29
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.65
</td>
<td style="text-align:left;">
.588
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
selfdisciplined
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
2.87
</td>
<td style="text-align:right;">
0.96
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.72
</td>
<td style="text-align:left;">
.545
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
softhearted
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.25
</td>
<td style="text-align:right;">
0.42
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.30
</td>
<td style="text-align:left;">
.828
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
sophisticated
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.08
</td>
<td style="text-align:right;">
0.36
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.21
</td>
<td style="text-align:left;">
.887
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
sympathetic
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
3.42
</td>
<td style="text-align:right;">
1.14
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1.10
</td>
<td style="text-align:left;">
.363
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
talkative
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
18.53
</td>
<td style="text-align:right;">
6.18
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
3.19
</td>
<td style="text-align:left;">
.037
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
thorough
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.33
</td>
<td style="text-align:right;">
0.11
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.08
</td>
<td style="text-align:left;">
.968
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
thrifty
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
8.09
</td>
<td style="text-align:right;">
2.70
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2.06
</td>
<td style="text-align:left;">
.126
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
warm
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.71
</td>
<td style="text-align:right;">
0.24
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.20
</td>
<td style="text-align:left;">
.897
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
careless
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
18.23
</td>
<td style="text-align:right;">
6.08
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2.77
</td>
<td style="text-align:left;">
.058
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
impulsive
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
2.65
</td>
<td style="text-align:right;">
0.88
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.45
</td>
<td style="text-align:left;">
.716
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
moody
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
6.21
</td>
<td style="text-align:right;">
2.07
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1.14
</td>
<td style="text-align:left;">
.350
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
nervous
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
1.54
</td>
<td style="text-align:right;">
0.51
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.20
</td>
<td style="text-align:left;">
.893
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
reckless
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
5.14
</td>
<td style="text-align:right;">
1.71
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.65
</td>
<td style="text-align:left;">
.587
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
worrying
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
8.95
</td>
<td style="text-align:right;">
2.98
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1.25
</td>
<td style="text-align:left;">
.307
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
</tbody>
</table>
</div>
<div id="pairwise-t-tests-for-significant-anovas" class="section level3">
<h3>Pairwise t-tests for significant ANOVAs</h3>
<p>When format was a significant predictor of response for an item (using the un-adjusted <em>p</em>-value here), we follow up with pairwise comparisons of format. Here we identify the items which meet this criteria. In the manuscript proper, we will only report the results for items in which format was significant, even after applying the Holm correction.</p>
<pre class="r"><code>sig_item_b1 = summary_by_item_b1 %&gt;%
  filter(p.value &lt; .05)

sig_item_b1 = sig_item_b1$item
sig_item_b1</code></pre>
<pre><code>## [1] &quot;talkative&quot;</code></pre>
<p>Then we create models for each adjective. We use the <code>emmeans</code> package to perform pairwise comparisons, again with a Holm correction on the <em>p</em>-values. We also plot the means and 95% confidence intervals of each mean.</p>
<p><strong>This code will have to be changed after final data collection. It is not self-adapting!</strong></p>
</div>
<div id="talkative" class="section level3">
<h3>Talkative</h3>
<pre class="r"><code>talkative_model_b1 = item_block1 %&gt;%
  filter(item == &quot;talkative&quot;) %&gt;%
  lm(response~format, data = .)

talkative_em_b1 = emmeans(talkative_model_b1, &quot;format&quot;)
pairs(talkative_em_b1, adjust = &quot;holm&quot;) %&gt;%
  as_tibble() %&gt;%
  mutate(across( starts_with(&quot;p&quot;), printp )) %&gt;% # format p-values
  kable(booktabs = T,
        digits = 2,
        caption = &quot;Differences in response to Talkative by format (Block 1 data only)&quot;,
        col.names = c(&quot;Contrast&quot;, &quot;Difference in means&quot;, &quot;SE&quot;, &quot;df&quot;, &quot;t&quot;, &quot;p&quot;)) %&gt;%
  kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
Differences in response to Talkative by format (Block 1 data only)
</caption>
<thead>
<tr>
<th style="text-align:left;">
Contrast
</th>
<th style="text-align:right;">
Difference in means
</th>
<th style="text-align:right;">
SE
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:right;">
t
</th>
<th style="text-align:left;">
p
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Adjective Only - Am Adjective
</td>
<td style="text-align:right;">
-1.49
</td>
<td style="text-align:right;">
0.63
</td>
<td style="text-align:right;">
31
</td>
<td style="text-align:right;">
-2.39
</td>
<td style="text-align:left;">
.139
</td>
</tr>
<tr>
<td style="text-align:left;">
Adjective Only - Tend to be Adjective
</td>
<td style="text-align:right;">
-1.40
</td>
<td style="text-align:right;">
0.65
</td>
<td style="text-align:right;">
31
</td>
<td style="text-align:right;">
-2.16
</td>
<td style="text-align:left;">
.192
</td>
</tr>
<tr>
<td style="text-align:left;">
Adjective Only - Am someone who tends to be Adjective
</td>
<td style="text-align:right;">
0.01
</td>
<td style="text-align:right;">
0.67
</td>
<td style="text-align:right;">
31
</td>
<td style="text-align:right;">
0.02
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
Am Adjective - Tend to be Adjective
</td>
<td style="text-align:right;">
0.10
</td>
<td style="text-align:right;">
0.68
</td>
<td style="text-align:right;">
31
</td>
<td style="text-align:right;">
0.14
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
Am Adjective - Am someone who tends to be Adjective
</td>
<td style="text-align:right;">
1.51
</td>
<td style="text-align:right;">
0.70
</td>
<td style="text-align:right;">
31
</td>
<td style="text-align:right;">
2.15
</td>
<td style="text-align:left;">
.192
</td>
</tr>
<tr>
<td style="text-align:left;">
Tend to be Adjective - Am someone who tends to be Adjective
</td>
<td style="text-align:right;">
1.41
</td>
<td style="text-align:right;">
0.72
</td>
<td style="text-align:right;">
31
</td>
<td style="text-align:right;">
1.96
</td>
<td style="text-align:left;">
.192
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>plot_model(talkative_model_b1, type = &quot;pred&quot;, terms = c(&quot;format&quot;))</code></pre>
<div class="figure">
<img src="analysis_format_files/figure-html/analysis-format-12-1.png" alt="Average response to &quot;talkative&quot; by format (block 1 data only)" width="672" />
<p class="caption">
Average response to “talkative” by format (block 1 data only)
</p>
</div>
</div>
</div>
<div id="effect-of-format-block-1-and-2" class="section level2">
<h2>Effect of format (Block 1 and 2)</h2>
<p>We again test whether format is a significant predictor of response. However, here we use data from both Blocks 1 and 2. As a reminder, all participants were presented with all four formats during Block 2. We expect this model to have greater power than the previous model, due to both increased sample size (twice as many data points) and because participants now provide data to all four formats, instead of only one (i.e., a within-person analysis).</p>
<pre class="r"><code>items_12 = items_df %&gt;% filter(block %in% c(&quot;1&quot;,&quot;2&quot;))</code></pre>
<pre class="r"><code>mod.format_b2 = lmer(response~format + (1|proid),
                  data = items_12)
anova(mod.format_b2)</code></pre>
<pre><code>## Type III Analysis of Variance Table with Satterthwaite&#39;s method
##        Sum Sq Mean Sq NumDF  DenDF F value Pr(&gt;F)
## format 4.1445  1.3815     3 2104.9  0.9193 0.4307</code></pre>
<p>When examining both Block 1 and Block 2 data, item format was unassociated with participants’ responses to personality items <span class="math inline">\((F(3, 2,104.92) = 0.92, p = .431)\)</span>.</p>
<pre class="r"><code>plot_b2 = plot_model(mod.format_b2, type = &quot;pred&quot;)

plot_b2$format +
  labs(x = NULL,
       y = &quot;Average response&quot;,
       title = &quot;Average responses by item formatting (Block 1 and Block 2)&quot;) +
  theme_pubclean()</code></pre>
<div class="figure">
<img src="analysis_format_files/figure-html/analysis-format-16-1.png" alt="Predicted response on personality items by condition, using only Block 1 data." width="672" />
<p class="caption">
Predicted response on personality items by condition, using only Block 1 data.
</p>
</div>
<pre class="r"><code>means_by_group = items_12 %&gt;%
  group_by(format) %&gt;%
  summarise(m = mean(response),
            s = sd(response))

items_12 %&gt;%
  ggplot(aes(x = response, fill = format)) +
  geom_histogram(bins = 6, color = &quot;white&quot;) +
  geom_vline(aes(xintercept = m), data = means_by_group) +
  geom_text(aes(x = 1,
                y = 200,
                label = paste(&quot;M =&quot;, round(m,2),
                              &quot;\nSD =&quot;, round(s,2))),
            data = means_by_group,
            hjust =0,
            vjust = 1) +
  facet_wrap(~format) +
  guides(fill = &quot;none&quot;) +
  scale_x_continuous(breaks = 1:6) +
  labs(y = &quot;Number of particpants&quot;,
       title = &quot;Distribution of responses by format (Block 1 and Block 2)&quot;) +
  theme_pubr()</code></pre>
<div class="figure">
<img src="analysis_format_files/figure-html/analysis-format-17-1.png" alt="Distribution of responses by category, block 1 and block 2" width="672" />
<p class="caption">
Distribution of responses by category, block 1 and block 2
</p>
</div>
<div id="one-model-for-each-adjective-1" class="section level3">
<h3>One model for each adjective</h3>
<p>We can also repeat this analysis separately for each trait. We use the <code>anova</code> function to estimate the variability due to format and print the corresponding <em>F</em>-test.</p>
<pre class="r"><code>mod_by_item_b2 = items_12 %&gt;%
  group_by(item) %&gt;%
  nest() %&gt;%
  mutate(mod = map(data, ~lmer(response~format + (1|proid), data = .))) %&gt;%
  mutate(aov = map(mod, anova))</code></pre>
<p>To present these results, we use the <code>tidy</code> function to summarise the findings and extract just the <em>F</em>-test associated with the format variable. We calculate adjusted <em>p</em>-values using a Holm correction. We also create a column that indicates whether the item was reverse-scored; we use this to sort the table, in case a pattern emerges.</p>
<pre class="r"><code>summary_by_item_b2 = mod_by_item_b2 %&gt;%
  ungroup() %&gt;%
  mutate(tidy = map(aov, broom::tidy)) %&gt;%
  select(item, tidy) %&gt;%
  unnest(cols = c(tidy)) %&gt;%
  filter(term == &quot;format&quot;) %&gt;%
  mutate(reverse = case_when(
    item %in% reverse ~ &quot;Y&quot;,
    TRUE ~ &quot;N&quot;
  )) %&gt;%
  mutate(p.adj = p.adjust(p.value, method = &quot;holm&quot;))

summary_by_item_b2 %&gt;%
  mutate(across( starts_with(&quot;p&quot;), printp )) %&gt;% # format p-values
  arrange(reverse, item) %&gt;%
  select(item, reverse, sumsq, meansq, NumDF, DenDF, statistic, p.value, p.adj) %&gt;%
  kable(digits = 2,
        col.names = c(&quot;Item&quot;, &quot;Reverse\nScored?&quot;, &quot;SS&quot;, &quot;MS&quot;, &quot;df1&quot;, &quot;df2&quot;, &quot;F&quot;, &quot;raw&quot;, &quot;adj&quot;),
        booktabs = T, caption = &quot;Format effects on response by item (block 1 data only)&quot;) %&gt;%
  kable_styling() %&gt;%
    add_header_above(c(&quot; &quot; = 7, &quot;p-value&quot; = 2))</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
Format effects on response by item (block 1 data only)
</caption>
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="7">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
p-value
</div>
</th>
</tr>
<tr>
<th style="text-align:left;">
Item
</th>
<th style="text-align:left;">
Reverse Scored?
</th>
<th style="text-align:right;">
SS
</th>
<th style="text-align:right;">
MS
</th>
<th style="text-align:right;">
df1
</th>
<th style="text-align:right;">
df2
</th>
<th style="text-align:right;">
F
</th>
<th style="text-align:left;">
raw
</th>
<th style="text-align:left;">
adj
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
active
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.76
</td>
<td style="text-align:right;">
0.25
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
40.00
</td>
<td style="text-align:right;">
1.01
</td>
<td style="text-align:left;">
.398
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
adventurous
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.51
</td>
<td style="text-align:right;">
0.50
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
48.65
</td>
<td style="text-align:right;">
1.09
</td>
<td style="text-align:left;">
.361
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
broadminded
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.54
</td>
<td style="text-align:right;">
0.51
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
64.49
</td>
<td style="text-align:right;">
0.76
</td>
<td style="text-align:left;">
.521
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
calm
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.13
</td>
<td style="text-align:right;">
0.04
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
45.02
</td>
<td style="text-align:right;">
0.13
</td>
<td style="text-align:left;">
.940
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
caring
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.16
</td>
<td style="text-align:right;">
0.39
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
52.66
</td>
<td style="text-align:right;">
1.28
</td>
<td style="text-align:left;">
.291
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
cautious
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
2.30
</td>
<td style="text-align:right;">
0.77
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
54.97
</td>
<td style="text-align:right;">
0.98
</td>
<td style="text-align:left;">
.407
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
creative
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.14
</td>
<td style="text-align:right;">
0.05
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
49.22
</td>
<td style="text-align:right;">
0.13
</td>
<td style="text-align:left;">
.943
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
curious
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
2.35
</td>
<td style="text-align:right;">
0.78
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
52.00
</td>
<td style="text-align:right;">
1.05
</td>
<td style="text-align:left;">
.377
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
friendly
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.94
</td>
<td style="text-align:right;">
0.31
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
46.85
</td>
<td style="text-align:right;">
1.45
</td>
<td style="text-align:left;">
.239
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
hardworking
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
2.10
</td>
<td style="text-align:right;">
0.70
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
52.03
</td>
<td style="text-align:right;">
2.06
</td>
<td style="text-align:left;">
.117
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
helpful
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.90
</td>
<td style="text-align:right;">
0.30
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
60.54
</td>
<td style="text-align:right;">
0.82
</td>
<td style="text-align:left;">
.488
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
imaginative
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.03
</td>
<td style="text-align:right;">
0.34
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
55.07
</td>
<td style="text-align:right;">
0.86
</td>
<td style="text-align:left;">
.465
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
intelligent
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.72
</td>
<td style="text-align:right;">
0.57
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
51.16
</td>
<td style="text-align:right;">
1.15
</td>
<td style="text-align:left;">
.340
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
lively
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.08
</td>
<td style="text-align:right;">
0.36
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
42.77
</td>
<td style="text-align:right;">
0.89
</td>
<td style="text-align:left;">
.456
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
organized
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.22
</td>
<td style="text-align:right;">
0.07
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
37.39
</td>
<td style="text-align:right;">
0.41
</td>
<td style="text-align:left;">
.750
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
outgoing
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.71
</td>
<td style="text-align:right;">
0.24
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
39.34
</td>
<td style="text-align:right;">
0.83
</td>
<td style="text-align:left;">
.484
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
responsible
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.51
</td>
<td style="text-align:right;">
0.50
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
56.50
</td>
<td style="text-align:right;">
0.82
</td>
<td style="text-align:left;">
.487
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
selfdisciplined
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.32
</td>
<td style="text-align:right;">
0.11
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
41.84
</td>
<td style="text-align:right;">
0.26
</td>
<td style="text-align:left;">
.853
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
softhearted
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.95
</td>
<td style="text-align:right;">
0.65
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
57.46
</td>
<td style="text-align:right;">
0.74
</td>
<td style="text-align:left;">
.531
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
sophisticated
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.05
</td>
<td style="text-align:right;">
0.02
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
44.04
</td>
<td style="text-align:right;">
0.04
</td>
<td style="text-align:left;">
.989
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
sympathetic
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.49
</td>
<td style="text-align:right;">
0.16
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
51.48
</td>
<td style="text-align:right;">
0.51
</td>
<td style="text-align:left;">
.676
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
talkative
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
6.36
</td>
<td style="text-align:right;">
2.12
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
43.86
</td>
<td style="text-align:right;">
1.95
</td>
<td style="text-align:left;">
.135
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
thorough
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
2.23
</td>
<td style="text-align:right;">
0.74
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
40.16
</td>
<td style="text-align:right;">
2.72
</td>
<td style="text-align:left;">
.057
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
thrifty
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
6.39
</td>
<td style="text-align:right;">
2.13
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
51.69
</td>
<td style="text-align:right;">
3.30
</td>
<td style="text-align:left;">
.027
</td>
<td style="text-align:left;">
.849
</td>
</tr>
<tr>
<td style="text-align:left;">
warm
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.10
</td>
<td style="text-align:right;">
0.03
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
52.22
</td>
<td style="text-align:right;">
0.08
</td>
<td style="text-align:left;">
.968
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
careless
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
8.29
</td>
<td style="text-align:right;">
2.76
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
53.32
</td>
<td style="text-align:right;">
2.84
</td>
<td style="text-align:left;">
.047
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
impulsive
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
1.38
</td>
<td style="text-align:right;">
0.46
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
41.41
</td>
<td style="text-align:right;">
0.85
</td>
<td style="text-align:left;">
.473
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
moody
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
1.21
</td>
<td style="text-align:right;">
0.40
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
42.77
</td>
<td style="text-align:right;">
0.69
</td>
<td style="text-align:left;">
.566
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
nervous
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
1.35
</td>
<td style="text-align:right;">
0.45
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
46.22
</td>
<td style="text-align:right;">
0.45
</td>
<td style="text-align:left;">
.716
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
reckless
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
1.14
</td>
<td style="text-align:right;">
0.38
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
48.60
</td>
<td style="text-align:right;">
0.36
</td>
<td style="text-align:left;">
.782
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
worrying
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
1.72
</td>
<td style="text-align:right;">
0.57
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
41.67
</td>
<td style="text-align:right;">
0.63
</td>
<td style="text-align:left;">
.602
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
</tbody>
</table>
</div>
<div id="pairwise-t-tests-for-significant-anovas-1" class="section level3">
<h3>Pairwise t-tests for significant ANOVAs</h3>
<p>Here we identify the specific items with significant differences.</p>
<pre class="r"><code>sig_item_b2 = summary_by_item_b2 %&gt;%
  filter(p.value &lt; .05)

sig_item_b2 = sig_item_b2$item
sig_item_b2</code></pre>
<pre><code>## [1] &quot;careless&quot; &quot;thrifty&quot;</code></pre>
<p>Then we create models for each adjective. We use the <code>emmeans</code> package to perform pairwise comparisons, again with a Holm correction on the <em>p</em>-values. We also plot the means and 95% confidence intervals of each mean.</p>
<p><strong>This code will have to be changed after final data collection. It is not self-adapting!</strong></p>
</div>
<div id="careless" class="section level3">
<h3>Careless</h3>
<pre class="r"><code>careless_model_b2 = items_12 %&gt;%
  filter(item == &quot;careless&quot;) %&gt;%
  lmer(response~format + (1|proid),
                               data = .)

careless_em_b2 = emmeans(careless_model_b2, &quot;format&quot;)
pairs(careless_em_b2, adjust = &quot;holm&quot;) %&gt;%
  as_tibble() %&gt;%
  mutate(across( starts_with(&quot;p&quot;), printp )) %&gt;% # format p-values
  kable(booktabs = T,
        digits = 2,
        caption = &quot;Differences in response to Careless by format (Block 1 and Block 2)&quot;,
        col.names = c(&quot;Contrast&quot;, &quot;Difference in means&quot;, &quot;SE&quot;, &quot;df&quot;, &quot;t&quot;, &quot;p&quot;)) %&gt;%
  kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
Differences in response to Careless by format (Block 1 and Block 2)
</caption>
<thead>
<tr>
<th style="text-align:left;">
Contrast
</th>
<th style="text-align:right;">
Difference in means
</th>
<th style="text-align:right;">
SE
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:right;">
t
</th>
<th style="text-align:left;">
p
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Adjective Only - Am Adjective
</td>
<td style="text-align:right;">
0.82
</td>
<td style="text-align:right;">
0.45
</td>
<td style="text-align:right;">
58.04
</td>
<td style="text-align:right;">
1.83
</td>
<td style="text-align:left;">
.359
</td>
</tr>
<tr>
<td style="text-align:left;">
Adjective Only - Tend to be Adjective
</td>
<td style="text-align:right;">
0.14
</td>
<td style="text-align:right;">
0.44
</td>
<td style="text-align:right;">
54.32
</td>
<td style="text-align:right;">
0.32
</td>
<td style="text-align:left;">
.749
</td>
</tr>
<tr>
<td style="text-align:left;">
Adjective Only - Am someone who tends to be Adjective
</td>
<td style="text-align:right;">
-0.44
</td>
<td style="text-align:right;">
0.44
</td>
<td style="text-align:right;">
54.32
</td>
<td style="text-align:right;">
-1.01
</td>
<td style="text-align:left;">
.633
</td>
</tr>
<tr>
<td style="text-align:left;">
Am Adjective - Tend to be Adjective
</td>
<td style="text-align:right;">
-0.68
</td>
<td style="text-align:right;">
0.45
</td>
<td style="text-align:right;">
51.43
</td>
<td style="text-align:right;">
-1.52
</td>
<td style="text-align:left;">
.542
</td>
</tr>
<tr>
<td style="text-align:left;">
Am Adjective - Am someone who tends to be Adjective
</td>
<td style="text-align:right;">
-1.26
</td>
<td style="text-align:right;">
0.45
</td>
<td style="text-align:right;">
51.43
</td>
<td style="text-align:right;">
-2.82
</td>
<td style="text-align:left;">
.041
</td>
</tr>
<tr>
<td style="text-align:left;">
Tend to be Adjective - Am someone who tends to be Adjective
</td>
<td style="text-align:right;">
-0.58
</td>
<td style="text-align:right;">
0.45
</td>
<td style="text-align:right;">
49.48
</td>
<td style="text-align:right;">
-1.31
</td>
<td style="text-align:left;">
.591
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>plot_model(careless_model_b2, type = &quot;pred&quot;, terms = c(&quot;format&quot;))</code></pre>
<div class="figure">
<img src="analysis_format_files/figure-html/analysis-format-22-1.png" alt="Average response to &quot;careless&quot; by format (Block 1 and Block 2)" width="672" />
<p class="caption">
Average response to “careless” by format (Block 1 and Block 2)
</p>
</div>
</div>
<div id="thrifty" class="section level3">
<h3>Thrifty</h3>
<pre class="r"><code>thrifty_model_b2 = items_12 %&gt;%
  filter(item == &quot;thrifty&quot;) %&gt;%
  lmer(response~format + (1|proid),
                               data = .)

thrifty_em_b2 = emmeans(thrifty_model_b2, &quot;format&quot;)
pairs(thrifty_em_b2, adjust = &quot;holm&quot;) %&gt;%
  as_tibble() %&gt;%
  mutate(across( starts_with(&quot;p&quot;), printp )) %&gt;% # format p-values
  kable(booktabs = T,
        digits = 2,
        caption = &quot;Differences in response to Thifty by format (Block 1 and Block 2)&quot;,
        col.names = c(&quot;Contrast&quot;, &quot;Difference in means&quot;, &quot;SE&quot;, &quot;df&quot;, &quot;t&quot;, &quot;p&quot;)) %&gt;%
  kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
Differences in response to Thifty by format (Block 1 and Block 2)
</caption>
<thead>
<tr>
<th style="text-align:left;">
Contrast
</th>
<th style="text-align:right;">
Difference in means
</th>
<th style="text-align:right;">
SE
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:right;">
t
</th>
<th style="text-align:left;">
p
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Adjective Only - Am Adjective
</td>
<td style="text-align:right;">
-0.02
</td>
<td style="text-align:right;">
0.36
</td>
<td style="text-align:right;">
56.66
</td>
<td style="text-align:right;">
-0.04
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
Adjective Only - Tend to be Adjective
</td>
<td style="text-align:right;">
-0.92
</td>
<td style="text-align:right;">
0.36
</td>
<td style="text-align:right;">
55.47
</td>
<td style="text-align:right;">
-2.54
</td>
<td style="text-align:left;">
.083
</td>
</tr>
<tr>
<td style="text-align:left;">
Adjective Only - Am someone who tends to be Adjective
</td>
<td style="text-align:right;">
-0.09
</td>
<td style="text-align:right;">
0.35
</td>
<td style="text-align:right;">
52.28
</td>
<td style="text-align:right;">
-0.26
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
Am Adjective - Tend to be Adjective
</td>
<td style="text-align:right;">
-0.90
</td>
<td style="text-align:right;">
0.37
</td>
<td style="text-align:right;">
56.24
</td>
<td style="text-align:right;">
-2.45
</td>
<td style="text-align:left;">
.084
</td>
</tr>
<tr>
<td style="text-align:left;">
Am Adjective - Am someone who tends to be Adjective
</td>
<td style="text-align:right;">
-0.08
</td>
<td style="text-align:right;">
0.37
</td>
<td style="text-align:right;">
54.54
</td>
<td style="text-align:right;">
-0.21
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
Tend to be Adjective - Am someone who tends to be Adjective
</td>
<td style="text-align:right;">
0.83
</td>
<td style="text-align:right;">
0.33
</td>
<td style="text-align:right;">
43.22
</td>
<td style="text-align:right;">
2.49
</td>
<td style="text-align:left;">
.084
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>plot_model(thrifty_model_b2, type = &quot;pred&quot;, terms = c(&quot;format&quot;))</code></pre>
<div class="figure">
<img src="analysis_format_files/figure-html/analysis-format-24-1.png" alt="Average response to &quot;thrifty&quot; by format (Block 1 and Block 2)" width="672" />
<p class="caption">
Average response to “thrifty” by format (Block 1 and Block 2)
</p>
</div>
</div>
</div>
<div id="account-for-memory-effects-blocks-1-and-2" class="section level2">
<h2>Account for memory effects (Blocks 1 and 2)</h2>
<p>One limitation of the two-blocks model is that format effects may depend on a person’s memory. For example, suppose that participants, in general, are more likely to respond with a 6 to items containing “tend to” (e.g., “tend to be outgoing”) than to items that only start with “am” (e.g., “am outgoing”). However, if a participant remembers that on the first presentation of the item they selected 4, they may be more likely choose 4 again to appear consistent. This example posits that memory moderates format’s effect on response. We model this possibility using participant’s delayed memory scores, or their recall score 10 minutes after seeing the list of words.</p>
<pre class="r"><code>mod.format_mem = lmer(response~format*delayed_memory + (1|proid),
                  data = items_12)
anova(mod.format_mem)</code></pre>
<pre><code>## Type III Analysis of Variance Table with Satterthwaite&#39;s method
##                       Sum Sq Mean Sq NumDF   DenDF F value Pr(&gt;F)
## format                4.8144 1.60479     3 2117.22  1.0675 0.3617
## delayed_memory        2.4823 2.48233     1   33.18  1.6513 0.2077
## format:delayed_memory 2.9060 0.96867     3 2118.52  0.6444 0.5865</code></pre>
<pre class="r"><code>summary(mod.format_mem)</code></pre>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: response ~ format * delayed_memory + (1 | proid)
##    Data: items_12
## 
## REML criterion at convergence: 7144.7
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.4343 -0.4565  0.2507  0.6893  1.7916 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  proid    (Intercept) 0.1804   0.4248  
##  Residual             1.5033   1.2261  
## Number of obs: 2170, groups:  proid, 35
## 
## Fixed effects:
##                                                               Estimate
## (Intercept)                                                    4.58932
## formatAm\nAdjective                                           -0.27329
## formatTend to be\nAdjective                                   -0.07698
## formatAm someone\nwho tends to be\nAdjective                  -0.14891
## delayed_memory                                                 0.01320
## formatAm\nAdjective:delayed_memory                             0.03632
## formatTend to be\nAdjective:delayed_memory                     0.02519
## formatAm someone\nwho tends to be\nAdjective:delayed_memory    0.02048
##                                                             Std. Error
## (Intercept)                                                    0.18198
## formatAm\nAdjective                                            0.15843
## formatTend to be\nAdjective                                    0.16694
## formatAm someone\nwho tends to be\nAdjective                   0.17237
## delayed_memory                                                 0.03108
## formatAm\nAdjective:delayed_memory                             0.02641
## formatTend to be\nAdjective:delayed_memory                     0.02944
## formatAm someone\nwho tends to be\nAdjective:delayed_memory    0.02956
##                                                                     df t value
## (Intercept)                                                   62.17156  25.219
## formatAm\nAdjective                                         2128.91591  -1.725
## formatTend to be\nAdjective                                 2092.17673  -0.461
## formatAm someone\nwho tends to be\nAdjective                2139.15284  -0.864
## delayed_memory                                                63.52491   0.425
## formatAm\nAdjective:delayed_memory                          2116.48721   1.375
## formatTend to be\nAdjective:delayed_memory                  2070.60879   0.856
## formatAm someone\nwho tends to be\nAdjective:delayed_memory 2147.54209   0.693
##                                                             Pr(&gt;|t|)    
## (Intercept)                                                   &lt;2e-16 ***
## formatAm\nAdjective                                           0.0847 .  
## formatTend to be\nAdjective                                   0.6447    
## formatAm someone\nwho tends to be\nAdjective                  0.3878    
## delayed_memory                                                0.6725    
## formatAm\nAdjective:delayed_memory                            0.1692    
## formatTend to be\nAdjective:delayed_memory                    0.3922    
## formatAm someone\nwho tends to be\nAdjective:delayed_memory   0.4885    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) frmtAA frTtbA frAswttbA dlyd_m frAA:_ fTtbA:
## frmtAmAdjct -0.439                                             
## frmtTndtbAd -0.433  0.478                                      
## frmtAswttbA -0.407  0.455  0.470                               
## delayd_mmry -0.869  0.387  0.381  0.355                        
## frmtAAdjc:_  0.397 -0.859 -0.433 -0.413    -0.465              
## frmtTtbAd:_  0.370 -0.409 -0.865 -0.398    -0.431  0.495       
## frAswttbA:_  0.354 -0.400 -0.410 -0.873    -0.410  0.484  0.460</code></pre>
<p>When examining both Block 1 and Block 2 data, memory did not have a main effect on participant responses <span class="math inline">\((F(1, 33.18) = 1.65, p = .208)\)</span> and did not moderate differences between formats <span class="math inline">\((F(3, 2,118.52) = 0.64, p = .586)\)</span>.</p>
<pre class="r"><code>plot_model(mod.format_mem,
           type = &quot;pred&quot;,
           term = c(&quot;format&quot;, &quot;delayed_memory[meansd]&quot;)) +
  geom_line() +
  labs(x = NULL,
       y = &quot;Average response&quot;) +
  scale_color_discrete(&quot;Memory&quot;, labels = c(&quot;-1SD&quot;, &quot;Mean&quot;, &quot;+1SD&quot;))+
  theme_pubclean()</code></pre>
<div class="figure">
<img src="analysis_format_files/figure-html/analysis-format-26-1.png" alt="Predicted response on personality items by condition after controlling for delayed_memory." width="672" />
<p class="caption">
Predicted response on personality items by condition after controlling for delayed_memory.
</p>
</div>
<div id="one-model-for-each-adjective-2" class="section level3">
<h3>One model for each adjective</h3>
<p>Again, we test this model within each trait adjective, to determine whether the moderating effect of memory is stronger for any particular trait(s).</p>
<pre class="r"><code>mod_by_item_mem = items_12 %&gt;%
  group_by(item) %&gt;%
  nest() %&gt;%
  mutate(mod = map(data, ~lm(response~format*delayed_memory, data = .))) %&gt;%
  mutate(aov = map(mod, anova))

summary_by_item_mem = mod_by_item_mem %&gt;%
  ungroup() %&gt;%
  mutate(tidy = map(aov, broom::tidy)) %&gt;%
  select(item, tidy) %&gt;%
  unnest(cols = c(tidy)) %&gt;%
  filter(term == &quot;format:delayed_memory&quot;) %&gt;%
  mutate(reverse = case_when(
    item %in% reverse ~ &quot;Y&quot;,
    TRUE ~ &quot;N&quot;
  )) %&gt;%
  mutate(p.adj = p.adjust(p.value, method = &quot;holm&quot;))

summary_by_item_mem %&gt;%
  mutate(across( starts_with(&quot;p&quot;), printp )) %&gt;% # format p-values
  arrange(reverse, item) %&gt;%
  select(item, reverse, sumsq, meansq, df, statistic, p.value, p.adj) %&gt;%
  kable(digits = 2,
         col.names = c(&quot;Item&quot;, &quot;Reverse\nScored?&quot;, &quot;SS&quot;, &quot;MS&quot;, &quot;df&quot;, &quot;F&quot;, &quot;raw&quot;, &quot;adj&quot;),
        booktabs = T) %&gt;%
  kable_styling() %&gt;%
  add_header_above(c(&quot; &quot; = 6, &quot;p-value&quot; = 2))</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="6">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
p-value
</div>
</th>
</tr>
<tr>
<th style="text-align:left;">
Item
</th>
<th style="text-align:left;">
Reverse Scored?
</th>
<th style="text-align:right;">
SS
</th>
<th style="text-align:right;">
MS
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:right;">
F
</th>
<th style="text-align:left;">
raw
</th>
<th style="text-align:left;">
adj
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
active
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.29
</td>
<td style="text-align:right;">
0.10
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.06
</td>
<td style="text-align:left;">
.980
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
adventurous
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.17
</td>
<td style="text-align:right;">
0.39
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.39
</td>
<td style="text-align:left;">
.759
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
broadminded
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.71
</td>
<td style="text-align:right;">
0.24
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.28
</td>
<td style="text-align:left;">
.843
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
calm
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.15
</td>
<td style="text-align:right;">
0.05
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.06
</td>
<td style="text-align:left;">
.980
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
caring
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.16
</td>
<td style="text-align:right;">
0.05
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.08
</td>
<td style="text-align:left;">
.968
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
cautious
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.42
</td>
<td style="text-align:right;">
0.14
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.12
</td>
<td style="text-align:left;">
.948
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
creative
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.12
</td>
<td style="text-align:right;">
0.37
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.44
</td>
<td style="text-align:left;">
.727
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
curious
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.28
</td>
<td style="text-align:right;">
0.43
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.27
</td>
<td style="text-align:left;">
.843
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
friendly
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.83
</td>
<td style="text-align:right;">
0.61
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1.01
</td>
<td style="text-align:left;">
.394
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
hardworking
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.74
</td>
<td style="text-align:right;">
0.25
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.37
</td>
<td style="text-align:left;">
.771
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
helpful
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.31
</td>
<td style="text-align:right;">
0.44
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.73
</td>
<td style="text-align:left;">
.536
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
imaginative
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.65
</td>
<td style="text-align:right;">
0.22
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.35
</td>
<td style="text-align:left;">
.790
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
intelligent
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
2.94
</td>
<td style="text-align:right;">
0.98
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.95
</td>
<td style="text-align:left;">
.421
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
lively
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.21
</td>
<td style="text-align:right;">
0.40
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.28
</td>
<td style="text-align:left;">
.840
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
organized
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
5.06
</td>
<td style="text-align:right;">
1.69
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1.53
</td>
<td style="text-align:left;">
.216
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
outgoing
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.72
</td>
<td style="text-align:right;">
0.57
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.40
</td>
<td style="text-align:left;">
.753
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
responsible
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
2.53
</td>
<td style="text-align:right;">
0.84
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1.11
</td>
<td style="text-align:left;">
.353
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
selfdisciplined
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
2.29
</td>
<td style="text-align:right;">
0.76
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.60
</td>
<td style="text-align:left;">
.616
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
softhearted
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.46
</td>
<td style="text-align:right;">
0.15
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.13
</td>
<td style="text-align:left;">
.943
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
sophisticated
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
4.21
</td>
<td style="text-align:right;">
1.40
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.89
</td>
<td style="text-align:left;">
.451
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
sympathetic
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.11
</td>
<td style="text-align:right;">
0.37
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.40
</td>
<td style="text-align:left;">
.754
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
talkative
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
8.53
</td>
<td style="text-align:right;">
2.84
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1.23
</td>
<td style="text-align:left;">
.306
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
thorough
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
3.87
</td>
<td style="text-align:right;">
1.29
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1.13
</td>
<td style="text-align:left;">
.344
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
thrifty
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.61
</td>
<td style="text-align:right;">
0.20
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.13
</td>
<td style="text-align:left;">
.940
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
warm
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.65
</td>
<td style="text-align:right;">
0.55
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.69
</td>
<td style="text-align:left;">
.560
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
careless
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
3.74
</td>
<td style="text-align:right;">
1.25
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.55
</td>
<td style="text-align:left;">
.653
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
impulsive
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
7.37
</td>
<td style="text-align:right;">
2.46
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1.13
</td>
<td style="text-align:left;">
.343
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
moody
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
10.15
</td>
<td style="text-align:right;">
3.38
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1.76
</td>
<td style="text-align:left;">
.165
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
nervous
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
4.40
</td>
<td style="text-align:right;">
1.47
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.57
</td>
<td style="text-align:left;">
.638
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
reckless
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
7.65
</td>
<td style="text-align:right;">
2.55
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1.01
</td>
<td style="text-align:left;">
.394
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
worrying
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
1.77
</td>
<td style="text-align:right;">
0.59
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.22
</td>
<td style="text-align:left;">
.880
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
</tbody>
</table>
</div>
<div id="pairwise-t-tests-for-significant-anovas-2" class="section level3">
<h3>Pairwise t-tests for significant ANOVAs</h3>
<p>Here we identify the specific items with significant differences.</p>
<pre class="r"><code>sig_item_mem = summary_by_item_mem %&gt;%
  filter(p.value &lt; .05)

sig_item_mem = sig_item_mem$item
sig_item_mem</code></pre>
<pre><code>## character(0)</code></pre>
</div>
</div>
<div id="inclusion-of-i-block-1-and-block-3" class="section level2">
<h2>Inclusion of “I” (Block 1 and Block 3)</h2>
<p>Finally, we test whether the inclusion of the word “I” impacts item response (e.g. “I am outgoing”). We used two multilevel models, nesting response within participant to account for dependence. Our primary predictors are format and also the presence of the word “I”. Because we have no specific rationale for how or why “I” would impact responses, we test both the partialled main effect of “I” as well as the interaction with format. Here, we use data from Blocks 1 and 3.</p>
<pre class="r"><code>items_13 = items_df %&gt;%
  filter(block %in% c(&quot;1&quot;,&quot;3&quot;)) %&gt;%
  filter(condition != &quot;A&quot;) %&gt;%
  filter(time2 == &quot;yes&quot;)</code></pre>
<pre class="r"><code>mod.format_b3_1 = lmer(response~format + i + (1|proid),
                  data = items_13)
anova(mod.format_b3_1)</code></pre>
<pre><code>## Type III Analysis of Variance Table with Satterthwaite&#39;s method
##        Sum Sq Mean Sq NumDF  DenDF F value Pr(&gt;F)
## format 2.4558  1.2279     2  13.00  0.8151 0.4640
## i      3.4314  3.4314     1 979.33  2.2778 0.1316</code></pre>
<pre class="r"><code>mod.format_b3_2 = lmer(response~format*i + (1|proid),
                  data = items_13)
anova(mod.format_b3_2)</code></pre>
<pre><code>## Type III Analysis of Variance Table with Satterthwaite&#39;s method
##          Sum Sq Mean Sq NumDF  DenDF F value Pr(&gt;F)
## format   3.3194 1.65969     2  14.78  1.1006 0.3584
## i        1.7404 1.74044     1 976.53  1.1542 0.2829
## format:i 1.5669 0.78345     2 976.81  0.5195 0.5950</code></pre>
<pre class="r"><code>plot_b3 = plot_model(mod.format_b3_2, type = &quot;pred&quot;, terms = c(&quot;format&quot;, &quot;i&quot;))
plot_b3 +
  geom_line() +
  labs(x = NULL,
       y = &quot;Average response&quot;,
       title = &quot;Average responses by item formatting (Block 1 and Block 2)&quot;) +
  theme_pubclean()</code></pre>
<div class="figure">
<img src="analysis_format_files/figure-html/analysis-format-32-1.png" alt="Predicted response on personality items by condition, using only Block 1 data." width="672" />
<p class="caption">
Predicted response on personality items by condition, using only Block 1 data.
</p>
</div>
<pre class="r"><code>means_by_group = items_13 %&gt;%
  group_by(format, i) %&gt;%
  summarise(m = mean(response),
            s = sd(response))

items_13 %&gt;%
  ggplot(aes(x = response, fill = i)) +
  geom_histogram(bins = 6, color = &quot;white&quot;) +
  geom_vline(aes(xintercept = m), data = means_by_group) +
  geom_text(aes(x = 1,
                y = 100,
                label = paste(&quot;M =&quot;, round(m,2),
                              &quot;\nSD =&quot;, round(s,2))),
            data = means_by_group,
            hjust =0,
            vjust = 1) +
  facet_grid(i~format, scales = &quot;free&quot;) +
  guides(fill = &quot;none&quot;) +
  scale_x_continuous(breaks = 1:6) +
  labs(y = &quot;Number of particpants&quot;,
       title = &quot;Distribution of responses by format (Block 1 and Block 2)&quot;) +
  theme_pubr()</code></pre>
<div class="figure">
<img src="analysis_format_files/figure-html/analysis-format-33-1.png" alt="Distribution of responses by category, block 1 and block 2" width="672" />
<p class="caption">
Distribution of responses by category, block 1 and block 2
</p>
</div>
<div id="one-model-for-each-adjective-3" class="section level3">
<h3>One model for each adjective</h3>
<pre class="r"><code>mod_by_item_i = items_13 %&gt;%
  group_by(item) %&gt;%
  nest() %&gt;%
  mutate(mod = map(data, ~lmer(response~format + i + (1|proid), data = .))) %&gt;%
  mutate(aov = map(mod, anova))

summary_by_item_i = mod_by_item_i %&gt;%
  ungroup() %&gt;%
  mutate(tidy = map(aov, broom::tidy)) %&gt;%
  select(item, tidy) %&gt;%
  unnest(cols = c(tidy)) %&gt;%
  filter(term == &quot;i&quot;) %&gt;%
  mutate(reverse = case_when(
    item %in% reverse ~ &quot;Y&quot;,
    TRUE ~ &quot;N&quot;
  )) %&gt;%
  mutate(p.adj = p.adjust(p.value, method = &quot;holm&quot;))

summary_by_item_i %&gt;%
  mutate(across( starts_with(&quot;p&quot;), printp )) %&gt;% # format p-values
  arrange(reverse, item) %&gt;%
  select(item, reverse, sumsq, meansq, NumDF, DenDF, statistic, p.value, p.adj) %&gt;%
  kable(digits = 2,
        col.names = c(&quot;Item&quot;, &quot;Reverse\nScored?&quot;, &quot;SS&quot;, &quot;MS&quot;, &quot;df1&quot;, &quot;df2&quot;, &quot;F&quot;, &quot;raw&quot;, &quot;adj&quot;),
        booktabs = T, caption = &quot;Effect of \&quot;I\&quot; (block 1 and 3 data)&quot;) %&gt;%
  kable_styling() %&gt;%
    add_header_above(c(&quot; &quot; = 7, &quot;p-value&quot; = 2))</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
Effect of “I” (block 1 and 3 data)
</caption>
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="7">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
p-value
</div>
</th>
</tr>
<tr>
<th style="text-align:left;">
Item
</th>
<th style="text-align:left;">
Reverse Scored?
</th>
<th style="text-align:right;">
SS
</th>
<th style="text-align:right;">
MS
</th>
<th style="text-align:right;">
df1
</th>
<th style="text-align:right;">
df2
</th>
<th style="text-align:right;">
F
</th>
<th style="text-align:left;">
raw
</th>
<th style="text-align:left;">
adj
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
active
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.79
</td>
<td style="text-align:right;">
0.79
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
17.53
</td>
<td style="text-align:right;">
2.15
</td>
<td style="text-align:left;">
.161
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
adventurous
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.69
</td>
<td style="text-align:right;">
0.69
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
28.00
</td>
<td style="text-align:right;">
1.31
</td>
<td style="text-align:left;">
.262
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
broadminded
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.07
</td>
<td style="text-align:right;">
0.07
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
21.24
</td>
<td style="text-align:right;">
0.13
</td>
<td style="text-align:left;">
.718
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
calm
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
2.26
</td>
<td style="text-align:right;">
2.26
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
21.01
</td>
<td style="text-align:right;">
2.85
</td>
<td style="text-align:left;">
.106
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
caring
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.19
</td>
<td style="text-align:right;">
0.19
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
28.00
</td>
<td style="text-align:right;">
0.63
</td>
<td style="text-align:left;">
.433
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
cautious
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.59
</td>
<td style="text-align:right;">
0.59
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
18.73
</td>
<td style="text-align:right;">
0.97
</td>
<td style="text-align:left;">
.337
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
creative
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.53
</td>
<td style="text-align:right;">
0.53
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
16.63
</td>
<td style="text-align:right;">
2.22
</td>
<td style="text-align:left;">
.155
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
curious
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.16
</td>
<td style="text-align:right;">
0.16
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
19.78
</td>
<td style="text-align:right;">
0.20
</td>
<td style="text-align:left;">
.664
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
friendly
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
28.00
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:left;">
.971
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
hardworking
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
17.35
</td>
<td style="text-align:right;">
0.04
</td>
<td style="text-align:left;">
.850
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
helpful
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.11
</td>
<td style="text-align:right;">
0.11
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
23.35
</td>
<td style="text-align:right;">
0.70
</td>
<td style="text-align:left;">
.410
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
imaginative
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.08
</td>
<td style="text-align:right;">
0.08
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
20.83
</td>
<td style="text-align:right;">
0.31
</td>
<td style="text-align:left;">
.582
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
intelligent
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.02
</td>
<td style="text-align:right;">
0.02
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
18.94
</td>
<td style="text-align:right;">
0.10
</td>
<td style="text-align:left;">
.755
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
lively
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
4.35
</td>
<td style="text-align:right;">
4.35
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
18.29
</td>
<td style="text-align:right;">
13.11
</td>
<td style="text-align:left;">
.002
</td>
<td style="text-align:left;">
.059
</td>
</tr>
<tr>
<td style="text-align:left;">
organized
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.29
</td>
<td style="text-align:right;">
0.29
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
16.69
</td>
<td style="text-align:right;">
0.91
</td>
<td style="text-align:left;">
.354
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
outgoing
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.18
</td>
<td style="text-align:right;">
0.18
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
17.41
</td>
<td style="text-align:right;">
0.62
</td>
<td style="text-align:left;">
.440
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
responsible
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.24
</td>
<td style="text-align:right;">
0.24
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
21.98
</td>
<td style="text-align:right;">
0.74
</td>
<td style="text-align:left;">
.399
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
selfdisciplined
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.17
</td>
<td style="text-align:right;">
0.17
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
17.30
</td>
<td style="text-align:right;">
1.13
</td>
<td style="text-align:left;">
.303
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
softhearted
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.91
</td>
<td style="text-align:right;">
0.91
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
21.21
</td>
<td style="text-align:right;">
0.69
</td>
<td style="text-align:left;">
.415
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
sophisticated
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.45
</td>
<td style="text-align:right;">
0.45
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
17.51
</td>
<td style="text-align:right;">
0.79
</td>
<td style="text-align:left;">
.385
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
sympathetic
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.60
</td>
<td style="text-align:right;">
0.60
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
20.31
</td>
<td style="text-align:right;">
1.17
</td>
<td style="text-align:left;">
.293
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
talkative
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.42
</td>
<td style="text-align:right;">
0.42
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
16.66
</td>
<td style="text-align:right;">
0.77
</td>
<td style="text-align:left;">
.394
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
thorough
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.64
</td>
<td style="text-align:right;">
1.64
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
20.01
</td>
<td style="text-align:right;">
5.48
</td>
<td style="text-align:left;">
.030
</td>
<td style="text-align:left;">
.893
</td>
</tr>
<tr>
<td style="text-align:left;">
thrifty
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.48
</td>
<td style="text-align:right;">
1.48
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
19.77
</td>
<td style="text-align:right;">
1.78
</td>
<td style="text-align:left;">
.197
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
warm
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
20.23
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:left;">
.967
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
careless
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
1.34
</td>
<td style="text-align:right;">
1.34
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
26.28
</td>
<td style="text-align:right;">
0.60
</td>
<td style="text-align:left;">
.446
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
impulsive
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
0.13
</td>
<td style="text-align:right;">
0.13
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
17.64
</td>
<td style="text-align:right;">
0.16
</td>
<td style="text-align:left;">
.693
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
moody
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
0.39
</td>
<td style="text-align:right;">
0.39
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
20.49
</td>
<td style="text-align:right;">
0.40
</td>
<td style="text-align:left;">
.534
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
nervous
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
3.24
</td>
<td style="text-align:right;">
3.24
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
26.54
</td>
<td style="text-align:right;">
1.89
</td>
<td style="text-align:left;">
.181
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
reckless
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
0.85
</td>
<td style="text-align:right;">
0.85
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
21.68
</td>
<td style="text-align:right;">
0.68
</td>
<td style="text-align:left;">
.420
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
worrying
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
0.01
</td>
<td style="text-align:right;">
0.01
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
20.29
</td>
<td style="text-align:right;">
0.01
</td>
<td style="text-align:left;">
.932
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>mod_by_item_i2 = items_13 %&gt;%
  group_by(item) %&gt;%
  nest() %&gt;%
  mutate(mod = map(data, ~lmer(response~format*i + (1|proid), data = .))) %&gt;%
  mutate(aov = map(mod, anova))

summary_by_item_i2 = mod_by_item_i2 %&gt;%
  ungroup() %&gt;%
  mutate(tidy = map(aov, broom::tidy)) %&gt;%
  select(item, tidy) %&gt;%
  unnest(cols = c(tidy)) %&gt;%
  filter(term == &quot;format:i&quot;) %&gt;%
  mutate(reverse = case_when(
    item %in% reverse ~ &quot;Y&quot;,
    TRUE ~ &quot;N&quot;
  )) %&gt;%
  mutate(p.adj = p.adjust(p.value, method = &quot;holm&quot;))

summary_by_item_i2 %&gt;%
  mutate(across( starts_with(&quot;p&quot;), printp )) %&gt;% # format p-values
  arrange(reverse, item) %&gt;%
  select(item, reverse, sumsq, meansq, NumDF, DenDF, statistic, p.value, p.adj) %&gt;%
  kable(digits = 2,
        col.names = c(&quot;Item&quot;, &quot;Reverse\nScored?&quot;, &quot;SS&quot;, &quot;MS&quot;, &quot;df1&quot;, &quot;df2&quot;, &quot;F&quot;, &quot;raw&quot;, &quot;adj&quot;),
        booktabs = T, caption = &quot;Interaction of format and \&quot;I\&quot; (block 1 and 3 data)&quot;) %&gt;%
  kable_styling() %&gt;%
    add_header_above(c(&quot; &quot; = 7, &quot;p-value&quot; = 2))</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
Interaction of format and “I” (block 1 and 3 data)
</caption>
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="7">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
p-value
</div>
</th>
</tr>
<tr>
<th style="text-align:left;">
Item
</th>
<th style="text-align:left;">
Reverse Scored?
</th>
<th style="text-align:right;">
SS
</th>
<th style="text-align:right;">
MS
</th>
<th style="text-align:right;">
df1
</th>
<th style="text-align:right;">
df2
</th>
<th style="text-align:right;">
F
</th>
<th style="text-align:left;">
raw
</th>
<th style="text-align:left;">
adj
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
active
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.65
</td>
<td style="text-align:right;">
0.32
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
15.11
</td>
<td style="text-align:right;">
0.76
</td>
<td style="text-align:left;">
.487
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
adventurous
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.49
</td>
<td style="text-align:right;">
0.75
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
22.11
</td>
<td style="text-align:right;">
1.52
</td>
<td style="text-align:left;">
.241
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
broadminded
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.95
</td>
<td style="text-align:right;">
0.97
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
20.88
</td>
<td style="text-align:right;">
1.94
</td>
<td style="text-align:left;">
.169
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
calm
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.31
</td>
<td style="text-align:right;">
0.16
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
20.67
</td>
<td style="text-align:right;">
0.18
</td>
<td style="text-align:left;">
.837
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
caring
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.27
</td>
<td style="text-align:right;">
0.13
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
26.00
</td>
<td style="text-align:right;">
0.43
</td>
<td style="text-align:left;">
.658
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
cautious
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.23
</td>
<td style="text-align:right;">
0.62
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
15.17
</td>
<td style="text-align:right;">
1.15
</td>
<td style="text-align:left;">
.344
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
creative
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.11
</td>
<td style="text-align:right;">
0.05
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
15.03
</td>
<td style="text-align:right;">
0.21
</td>
<td style="text-align:left;">
.812
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
curious
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
5.15
</td>
<td style="text-align:right;">
2.58
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
16.43
</td>
<td style="text-align:right;">
4.65
</td>
<td style="text-align:left;">
.025
</td>
<td style="text-align:left;">
.729
</td>
</tr>
<tr>
<td style="text-align:left;">
friendly
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.55
</td>
<td style="text-align:right;">
0.27
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
26.00
</td>
<td style="text-align:right;">
0.87
</td>
<td style="text-align:left;">
.431
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
hardworking
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.28
</td>
<td style="text-align:right;">
0.14
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
14.65
</td>
<td style="text-align:right;">
1.16
</td>
<td style="text-align:left;">
.342
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
helpful
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.23
</td>
<td style="text-align:right;">
0.12
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
21.45
</td>
<td style="text-align:right;">
0.69
</td>
<td style="text-align:left;">
.515
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
imaginative
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.29
</td>
<td style="text-align:right;">
0.15
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
19.61
</td>
<td style="text-align:right;">
0.51
</td>
<td style="text-align:left;">
.608
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
intelligent
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.07
</td>
<td style="text-align:right;">
0.04
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
16.71
</td>
<td style="text-align:right;">
0.16
</td>
<td style="text-align:left;">
.854
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
lively
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
2.34
</td>
<td style="text-align:right;">
1.17
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
15.12
</td>
<td style="text-align:right;">
5.78
</td>
<td style="text-align:left;">
.014
</td>
<td style="text-align:left;">
.413
</td>
</tr>
<tr>
<td style="text-align:left;">
organized
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.33
</td>
<td style="text-align:right;">
0.16
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
15.11
</td>
<td style="text-align:right;">
0.48
</td>
<td style="text-align:left;">
.629
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
outgoing
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.26
</td>
<td style="text-align:right;">
0.26
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
16.27
</td>
<td style="text-align:right;">
0.90
</td>
<td style="text-align:left;">
.356
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
responsible
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
2.07
</td>
<td style="text-align:right;">
1.03
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
19.58
</td>
<td style="text-align:right;">
4.17
</td>
<td style="text-align:left;">
.031
</td>
<td style="text-align:left;">
.869
</td>
</tr>
<tr>
<td style="text-align:left;">
selfdisciplined
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.47
</td>
<td style="text-align:right;">
0.23
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
14.86
</td>
<td style="text-align:right;">
1.65
</td>
<td style="text-align:left;">
.225
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
softhearted
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
10.15
</td>
<td style="text-align:right;">
5.08
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
20.14
</td>
<td style="text-align:right;">
3.69
</td>
<td style="text-align:left;">
.043
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
sophisticated
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.96
</td>
<td style="text-align:right;">
0.98
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
15.26
</td>
<td style="text-align:right;">
1.96
</td>
<td style="text-align:left;">
.174
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
sympathetic
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
3.24
</td>
<td style="text-align:right;">
1.62
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
14.45
</td>
<td style="text-align:right;">
5.91
</td>
<td style="text-align:left;">
.013
</td>
<td style="text-align:left;">
.413
</td>
</tr>
<tr>
<td style="text-align:left;">
talkative
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.17
</td>
<td style="text-align:right;">
0.08
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
14.68
</td>
<td style="text-align:right;">
0.13
</td>
<td style="text-align:left;">
.875
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
thorough
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.01
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
18.49
</td>
<td style="text-align:right;">
0.01
</td>
<td style="text-align:left;">
.988
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
thrifty
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
1.22
</td>
<td style="text-align:right;">
0.61
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
17.82
</td>
<td style="text-align:right;">
0.70
</td>
<td style="text-align:left;">
.509
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
warm
</td>
<td style="text-align:left;">
N
</td>
<td style="text-align:right;">
0.45
</td>
<td style="text-align:right;">
0.23
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
18.90
</td>
<td style="text-align:right;">
0.40
</td>
<td style="text-align:left;">
.673
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
careless
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
9.07
</td>
<td style="text-align:right;">
4.54
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
24.69
</td>
<td style="text-align:right;">
2.16
</td>
<td style="text-align:left;">
.137
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
impulsive
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
0.06
</td>
<td style="text-align:right;">
0.03
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
15.73
</td>
<td style="text-align:right;">
0.03
</td>
<td style="text-align:left;">
.966
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
moody
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
1.12
</td>
<td style="text-align:right;">
0.56
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
17.91
</td>
<td style="text-align:right;">
0.55
</td>
<td style="text-align:left;">
.587
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
nervous
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
1.35
</td>
<td style="text-align:right;">
0.67
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
23.48
</td>
<td style="text-align:right;">
0.41
</td>
<td style="text-align:left;">
.667
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
reckless
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
2.37
</td>
<td style="text-align:right;">
1.18
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
18.59
</td>
<td style="text-align:right;">
1.05
</td>
<td style="text-align:left;">
.370
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
worrying
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
1.95
</td>
<td style="text-align:right;">
0.97
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
18.56
</td>
<td style="text-align:right;">
0.89
</td>
<td style="text-align:left;">
.429
</td>
<td style="text-align:left;">
&gt; .999
</td>
</tr>
</tbody>
</table>
</div>
<div id="pairwise-t-tests-for-significant-anovas-3" class="section level3">
<h3>Pairwise t-tests for significant ANOVAs</h3>
<p>Here we identify the specific items with significant differences.</p>
<pre class="r"><code>sig_item_i = summary_by_item_i %&gt;%
  filter(p.value &lt; .05)

sig_item_i = sig_item_i$item
sig_item_i</code></pre>
<pre><code>## [1] &quot;lively&quot;   &quot;thorough&quot;</code></pre>
</div>
<div id="curious" class="section level3">
<h3>Curious</h3>
<pre class="r"><code>curious_model_i = items_13 %&gt;%
  filter(item == &quot;curious&quot;) %&gt;%
  lmer(response~format*i + (1|proid),
                               data = .)

curious_model_i %&gt;%
  tidy() %&gt;%
  mutate(term = str_replace(term, &quot;\n&quot;, &quot; &quot;),
         term = str_replace(term, &quot;format&quot;, &quot;&quot;),
         term = str_replace(term, &quot;iPresent&quot;, &quot;I&quot;)) %&gt;%
  filter(is.na(group)) %&gt;%
  select(-effect, -group) %&gt;%
  mutate(across( starts_with(&quot;p&quot;), printp )) %&gt;% # format p-values
  kable(booktabs = T,
        digits = 2,
        caption = &quot;Interaction of format and \&quot;I\&quot;&quot;,
        col.names = c(&quot;Term&quot;, &quot;Estimate&quot;, &quot;SE&quot;,  &quot;t&quot;, &quot;df&quot;, &quot;p&quot;)) %&gt;%
  kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
Interaction of format and “I”
</caption>
<thead>
<tr>
<th style="text-align:left;">
Term
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
SE
</th>
<th style="text-align:right;">
t
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:left;">
p
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
5.07
</td>
<td style="text-align:right;">
0.41
</td>
<td style="text-align:right;">
12.22
</td>
<td style="text-align:right;">
15.50
</td>
<td style="text-align:left;">
&lt; .001
</td>
</tr>
<tr>
<td style="text-align:left;">
Tend to be Adjective
</td>
<td style="text-align:right;">
-0.48
</td>
<td style="text-align:right;">
0.60
</td>
<td style="text-align:right;">
-0.79
</td>
<td style="text-align:right;">
14.75
</td>
<td style="text-align:left;">
.440
</td>
</tr>
<tr>
<td style="text-align:left;">
Am someone who tends to be Adjective
</td>
<td style="text-align:right;">
-0.18
</td>
<td style="text-align:right;">
0.76
</td>
<td style="text-align:right;">
-0.24
</td>
<td style="text-align:right;">
15.96
</td>
<td style="text-align:left;">
.816
</td>
</tr>
<tr>
<td style="text-align:left;">
I
</td>
<td style="text-align:right;">
0.77
</td>
<td style="text-align:right;">
0.50
</td>
<td style="text-align:right;">
1.53
</td>
<td style="text-align:right;">
16.12
</td>
<td style="text-align:left;">
.145
</td>
</tr>
<tr>
<td style="text-align:left;">
Tend to be Adjective:I
</td>
<td style="text-align:right;">
0.20
</td>
<td style="text-align:right;">
0.85
</td>
<td style="text-align:right;">
0.23
</td>
<td style="text-align:right;">
17.12
</td>
<td style="text-align:left;">
.819
</td>
</tr>
<tr>
<td style="text-align:left;">
Am someone who tends to be Adjective:I
</td>
<td style="text-align:right;">
-2.43
</td>
<td style="text-align:right;">
0.87
</td>
<td style="text-align:right;">
-2.78
</td>
<td style="text-align:right;">
15.68
</td>
<td style="text-align:left;">
.013
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>plot_model(curious_model_i, type = &quot;pred&quot;,
           terms = c(&quot;format&quot;, &quot;i&quot;)) +
  geom_line()</code></pre>
<p><img src="analysis_format_files/figure-html/analysis-format-38-1.png" width="672" /></p>
</div>
<div id="lively" class="section level3">
<h3>Lively</h3>
<pre class="r"><code>lively_model_i = items_13 %&gt;%
  filter(item == &quot;lively&quot;) %&gt;%
  lmer(response~format*i + (1|proid),
                               data = .)

lively_model_i %&gt;%
  tidy() %&gt;%
  mutate(term = str_replace(term, &quot;\n&quot;, &quot; &quot;),
         term = str_replace(term, &quot;format&quot;, &quot;&quot;),
         term = str_replace(term, &quot;iPresent&quot;, &quot;I&quot;)) %&gt;%
  filter(is.na(group)) %&gt;%
  select(-effect, -group) %&gt;%
  mutate(across( starts_with(&quot;p&quot;), printp )) %&gt;% # format p-values
  kable(booktabs = T,
        digits = 2,
        caption = &quot;Interaction of format and \&quot;I\&quot;&quot;,
        col.names = c(&quot;Term&quot;, &quot;Estimate&quot;, &quot;SE&quot;,  &quot;t&quot;, &quot;df&quot;, &quot;p&quot;)) %&gt;%
  kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
Interaction of format and “I”
</caption>
<thead>
<tr>
<th style="text-align:left;">
Term
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
SE
</th>
<th style="text-align:right;">
t
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:left;">
p
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
4.87
</td>
<td style="text-align:right;">
0.36
</td>
<td style="text-align:right;">
13.58
</td>
<td style="text-align:right;">
14.04
</td>
<td style="text-align:left;">
&lt; .001
</td>
</tr>
<tr>
<td style="text-align:left;">
Tend to be Adjective
</td>
<td style="text-align:right;">
0.22
</td>
<td style="text-align:right;">
0.53
</td>
<td style="text-align:right;">
0.42
</td>
<td style="text-align:right;">
14.15
</td>
<td style="text-align:left;">
.681
</td>
</tr>
<tr>
<td style="text-align:left;">
Am someone who tends to be Adjective
</td>
<td style="text-align:right;">
0.65
</td>
<td style="text-align:right;">
0.65
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
13.85
</td>
<td style="text-align:left;">
.334
</td>
</tr>
<tr>
<td style="text-align:left;">
I
</td>
<td style="text-align:right;">
-1.38
</td>
<td style="text-align:right;">
0.36
</td>
<td style="text-align:right;">
-3.86
</td>
<td style="text-align:right;">
15.06
</td>
<td style="text-align:left;">
.002
</td>
</tr>
<tr>
<td style="text-align:left;">
Tend to be Adjective:I
</td>
<td style="text-align:right;">
0.02
</td>
<td style="text-align:right;">
0.50
</td>
<td style="text-align:right;">
0.05
</td>
<td style="text-align:right;">
14.95
</td>
<td style="text-align:left;">
.963
</td>
</tr>
<tr>
<td style="text-align:left;">
Am someone who tends to be Adjective:I
</td>
<td style="text-align:right;">
2.27
</td>
<td style="text-align:right;">
0.71
</td>
<td style="text-align:right;">
3.20
</td>
<td style="text-align:right;">
15.27
</td>
<td style="text-align:left;">
.006
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>plot_model(lively_model_i, type = &quot;pred&quot;,
           terms = c(&quot;format&quot;, &quot;i&quot;)) +
  geom_line()</code></pre>
<p><img src="analysis_format_files/figure-html/analysis-format-40-1.png" width="672" /></p>
</div>
<div id="responsible" class="section level3">
<h3>Responsible</h3>
<pre class="r"><code>responsible_model_i = items_13 %&gt;%
  filter(item == &quot;responsible&quot;) %&gt;%
  lmer(response~format*i + (1|proid),
                               data = .)

responsible_model_i %&gt;%
  tidy() %&gt;%
  mutate(term = str_replace(term, &quot;\n&quot;, &quot; &quot;),
         term = str_replace(term, &quot;format&quot;, &quot;&quot;),
         term = str_replace(term, &quot;iPresent&quot;, &quot;I&quot;)) %&gt;%
  filter(is.na(group)) %&gt;%
  select(-effect, -group) %&gt;%
  mutate(across( starts_with(&quot;p&quot;), printp )) %&gt;% # format p-values
  kable(booktabs = T,
        digits = 2,
        caption = &quot;Interaction of format and \&quot;I\&quot;&quot;,
        col.names = c(&quot;Term&quot;, &quot;Estimate&quot;, &quot;SE&quot;,  &quot;t&quot;, &quot;df&quot;, &quot;p&quot;)) %&gt;%
  kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
Interaction of format and “I”
</caption>
<thead>
<tr>
<th style="text-align:left;">
Term
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
SE
</th>
<th style="text-align:right;">
t
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:left;">
p
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
5.50
</td>
<td style="text-align:right;">
0.21
</td>
<td style="text-align:right;">
26.30
</td>
<td style="text-align:right;">
16.71
</td>
<td style="text-align:left;">
&lt; .001
</td>
</tr>
<tr>
<td style="text-align:left;">
Tend to be Adjective
</td>
<td style="text-align:right;">
-0.04
</td>
<td style="text-align:right;">
0.31
</td>
<td style="text-align:right;">
-0.11
</td>
<td style="text-align:right;">
17.32
</td>
<td style="text-align:left;">
.910
</td>
</tr>
<tr>
<td style="text-align:left;">
Am someone who tends to be Adjective
</td>
<td style="text-align:right;">
0.06
</td>
<td style="text-align:right;">
0.37
</td>
<td style="text-align:right;">
0.17
</td>
<td style="text-align:right;">
15.13
</td>
<td style="text-align:left;">
.868
</td>
</tr>
<tr>
<td style="text-align:left;">
I
</td>
<td style="text-align:right;">
0.25
</td>
<td style="text-align:right;">
0.32
</td>
<td style="text-align:right;">
0.78
</td>
<td style="text-align:right;">
18.85
</td>
<td style="text-align:left;">
.443
</td>
</tr>
<tr>
<td style="text-align:left;">
Tend to be Adjective:I
</td>
<td style="text-align:right;">
-1.14
</td>
<td style="text-align:right;">
0.46
</td>
<td style="text-align:right;">
-2.50
</td>
<td style="text-align:right;">
18.26
</td>
<td style="text-align:left;">
.022
</td>
</tr>
<tr>
<td style="text-align:left;">
Am someone who tends to be Adjective:I
</td>
<td style="text-align:right;">
0.38
</td>
<td style="text-align:right;">
0.69
</td>
<td style="text-align:right;">
0.55
</td>
<td style="text-align:right;">
20.83
</td>
<td style="text-align:left;">
.591
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>plot_model(responsible_model_i, type = &quot;pred&quot;,
           terms = c(&quot;format&quot;, &quot;i&quot;)) +
  geom_line()</code></pre>
<p><img src="analysis_format_files/figure-html/analysis-format-42-1.png" width="672" /></p>
</div>
<div id="sympathetic" class="section level3">
<h3>Sympathetic</h3>
<pre class="r"><code>sympathetic_model_i = items_13 %&gt;%
  filter(item == &quot;sympathetic&quot;) %&gt;%
  lmer(response~format*i + (1|proid),
                               data = .)

sympathetic_model_i %&gt;%
  tidy() %&gt;%
  mutate(term = str_replace(term, &quot;\n&quot;, &quot; &quot;),
         term = str_replace(term, &quot;format&quot;, &quot;&quot;),
         term = str_replace(term, &quot;iPresent&quot;, &quot;I&quot;)) %&gt;%
  filter(is.na(group)) %&gt;%
  select(-effect, -group) %&gt;%
  mutate(across( starts_with(&quot;p&quot;), printp )) %&gt;% # format p-values
  kable(booktabs = T,
        digits = 2,
        caption = &quot;Interaction of format and \&quot;I\&quot;&quot;,
        col.names = c(&quot;Term&quot;, &quot;Estimate&quot;, &quot;SE&quot;,  &quot;t&quot;, &quot;df&quot;, &quot;p&quot;)) %&gt;%
  kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
Interaction of format and “I”
</caption>
<thead>
<tr>
<th style="text-align:left;">
Term
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
SE
</th>
<th style="text-align:right;">
t
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:left;">
p
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
4.73
</td>
<td style="text-align:right;">
0.37
</td>
<td style="text-align:right;">
12.67
</td>
<td style="text-align:right;">
14.07
</td>
<td style="text-align:left;">
&lt; .001
</td>
</tr>
<tr>
<td style="text-align:left;">
Tend to be Adjective
</td>
<td style="text-align:right;">
0.27
</td>
<td style="text-align:right;">
0.54
</td>
<td style="text-align:right;">
0.50
</td>
<td style="text-align:right;">
13.60
</td>
<td style="text-align:left;">
.624
</td>
</tr>
<tr>
<td style="text-align:left;">
Am someone who tends to be Adjective
</td>
<td style="text-align:right;">
-0.50
</td>
<td style="text-align:right;">
0.68
</td>
<td style="text-align:right;">
-0.73
</td>
<td style="text-align:right;">
14.34
</td>
<td style="text-align:left;">
.480
</td>
</tr>
<tr>
<td style="text-align:left;">
I
</td>
<td style="text-align:right;">
-0.30
</td>
<td style="text-align:right;">
0.36
</td>
<td style="text-align:right;">
-0.82
</td>
<td style="text-align:right;">
14.25
</td>
<td style="text-align:left;">
.423
</td>
</tr>
<tr>
<td style="text-align:left;">
Tend to be Adjective:I
</td>
<td style="text-align:right;">
0.30
</td>
<td style="text-align:right;">
0.61
</td>
<td style="text-align:right;">
0.48
</td>
<td style="text-align:right;">
14.87
</td>
<td style="text-align:left;">
.637
</td>
</tr>
<tr>
<td style="text-align:left;">
Am someone who tends to be Adjective:I
</td>
<td style="text-align:right;">
2.10
</td>
<td style="text-align:right;">
0.62
</td>
<td style="text-align:right;">
3.37
</td>
<td style="text-align:right;">
13.99
</td>
<td style="text-align:left;">
.005
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>plot_model(sympathetic_model_i, type = &quot;pred&quot;,
           terms = c(&quot;format&quot;, &quot;i&quot;)) +
  geom_line()</code></pre>
<p><img src="analysis_format_files/figure-html/analysis-format-44-1.png" width="672" /></p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
