<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Device effects</title>

<script src="site_libs/header-attrs-2.10/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">On item wording effects</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="1-cleaning.html">Data cleaning</a>
</li>
<li>
  <a href="descriptives.html">Descriptives</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Analysis
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="analysis_format.html">Does item formatting affect response?</a>
    </li>
    <li>
      <a href="internal.html">Does item formatting affect internal consistency?</a>
    </li>
    <li>
      <a href="test_retest.html">Does item formatting affect test-retest reliability?</a>
    </li>
    <li>
      <a href="timing_format.html">Does timing differ across format?</a>
    </li>
    <li>
      <a href="device.html">Does device type affect response and timing?</a>
    </li>
  </ul>
</li>
<li>
  <a href="power.html">Power analysis</a>
</li>
<li>
  <a href="workspace.html">R version and packages</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/pie-lab/wording-effects">
    <span class="fa fa-github"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Device effects</h1>
<h4 class="date">Last updated 2021-08-24</h4>

</div>


<p>In this section, we present exploratory analyses which test the effect of device type More specifically, we’re interested to know whether the time it takes to complete personality assessments differs by device type (computer, phone, tablet). We also test whether the typical response to personality items is associated with device type, although we have no theoretical reasons to suspect this is the case.</p>
<p>For these analyses, we use only data collected in Blocks 1 and 2.</p>
<pre class="r"><code>items_12 = items_df %&gt;% filter(block %in% c(&quot;1&quot;,&quot;2&quot;))</code></pre>
<div id="demographics-by-device-type" class="section level2" number="0.1">
<h2><span class="header-section-number">0.1</span> Demographics by device type</h2>
<p>Device-type analyses in this project are purely exploratory, but may be hampered by potential confounds. We test whether different types of participants (based on demographic variables) used different devices to complete the survey.</p>
<p>Figure <a href="#fig:descriptives-17">1</a>A shows the distributions of age by device type; the ANOVA test of these differences is <span class="math inline">\(F(2, 32) = 0.05\)</span>, <span class="math inline">\(\mathit{MSE} = 38.33\)</span>, <span class="math inline">\(p = .953\)</span>, <span class="math inline">\(\hat{\eta}^2_G = .003\)</span>. The chi-square test of biological sex by device type was <span class="math inline">\(\chi^2(2, n = 35) = 2.83\)</span>, <span class="math inline">\(p = .243\)</span>.</p>
<div class="figure"><span style="display:block;" id="fig:descriptives-17"></span>
<img src="device_files/figure-html/descriptives-17-1.png" alt="Distributions by device type" width="672" />
<p class="caption">
Figure 1: Distributions by device type
</p>
</div>
</div>
<div id="timing" class="section level2" number="0.2">
<h2><span class="header-section-number">0.2</span> Timing</h2>
<div id="timing-by-device" class="section level3" number="0.2.1">
<h3><span class="header-section-number">0.2.1</span> Timing by device</h3>
<p>We used a multilevel model, nesting timing within participant to account for dependence. Our primary predictor was device type. As a reminder, our outcome variable (seconds) has been log-transformed, as it was strongly skewed.</p>
<pre class="r"><code>mod.timing = lmer(seconds_log~devicetype + (1|proid), 
                  data = items_12)
anova(mod.timing)</code></pre>
<pre><code>## Type III Analysis of Variance Table with Satterthwaite&#39;s method
##            Sum Sq Mean Sq NumDF DenDF F value Pr(&gt;F)
## devicetype 2.4781  1.2391     2    32  1.8444 0.1745</code></pre>
<p>When examining both Block 1 and Block 2 data, device type was unassociated with the time it took to respond to personality items <span class="math inline">\((F(2, 32.00) = 1.84, p = .175)\)</span>.</p>
<pre class="r"><code>plot1 = plot_model(mod.timing, type = &quot;pred&quot;) 

plot1$devicetype +
  labs(x = NULL,
       y = &quot;Log-seconds (per item)&quot;,
       title = &quot;Average time per personality item\nby device type&quot;,
       caption = &quot;Bars represent 95% confidence intervals&quot;) +
  theme_pubclean()</code></pre>
<div class="figure"><span style="display:block;" id="fig:device-7"></span>
<img src="device_files/figure-html/device-7-1.png" alt="Predicted timing on personality items by condition." width="672" />
<p class="caption">
Figure 2: Predicted timing on personality items by condition.
</p>
</div>
<pre class="r"><code>means_by_group = items_12 %&gt;%
  group_by(devicetype) %&gt;% 
  summarise(m = mean(timing),
            s = sd(timing))

items_12 %&gt;%
  ggplot(aes(x = timing, fill = devicetype)) +
  geom_histogram(bins = 100) +
  geom_vline(aes(xintercept = m), data = means_by_group) +
  facet_wrap(~devicetype, scales = &quot;free_y&quot;) +
  guides(fill = &quot;none&quot;) +
  scale_x_log10() +
  labs(y = &quot;Number of particpants&quot;,
       title = &quot;Distribution of timing by format&quot;,
       x = &quot;timing (logrithmic scale)&quot;) +
  theme_pubr()</code></pre>
<div class="figure"><span style="display:block;" id="fig:device-8"></span>
<img src="device_files/figure-html/device-8-1.png" alt="Distribution of secondss by category" width="672" />
<p class="caption">
Figure 3: Distribution of secondss by category
</p>
</div>
</div>
<div id="device-by-format" class="section level3" number="0.2.2">
<h3><span class="header-section-number">0.2.2</span> Device by format</h3>
<p>We also check to see whether device type and format interact in the prediction of time to answer personality items.</p>
<pre class="r"><code>mod.timing2 = lmer(seconds_log~devicetype*format + (1|proid), 
                  data = items_12)
anova(mod.timing2)</code></pre>
<pre><code>## Type III Analysis of Variance Table with Satterthwaite&#39;s method
##                   Sum Sq Mean Sq NumDF   DenDF F value    Pr(&gt;F)    
## devicetype         2.919  1.4595     2   32.31  2.2275 0.1240954    
## format            11.022  3.6741     3 2146.65  5.6074 0.0007915 ***
## devicetype:format 14.153  2.3589     6 2148.23  3.6001 0.0014831 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The interaction between device type and format was associated with the time it took to respond to personality items <span class="math inline">\((F(6, 2,148.23) = 3.60, p = .001)\)</span>.</p>
<pre class="r"><code>plot1 = plot_model(mod.timing2, type = &quot;pred&quot;, terms = c(&quot;format&quot;, &quot;devicetype&quot;)) 

plot1 +
  geom_line() +
  labs(x = NULL,
       y = &quot;Log-seconds (per item)&quot;,
       title = &quot;Average time per personality item\nby device type and item format&quot;,
       color = &quot;Device&quot;,
       caption = &quot;Bars represent 95% confidence intervals&quot;) +
  theme_pubclean()</code></pre>
<div class="figure"><span style="display:block;" id="fig:device-11"></span>
<img src="device_files/figure-html/device-11-1.png" alt="Predicted timing on personality items by condition." width="672" />
<p class="caption">
Figure 4: Predicted timing on personality items by condition.
</p>
</div>
</div>
</div>
<div id="responses" class="section level2" number="0.3">
<h2><span class="header-section-number">0.3</span> Responses</h2>
<p>Here we estimate the differences in response to personality items items by device. Again, we have no theoretical rationale for these models – these are purely exploratory.</p>
<div id="response-by-device" class="section level3" number="0.3.1">
<h3><span class="header-section-number">0.3.1</span> Response by device</h3>
<p>We used a multilevel model, nesting response within participant to account for dependence. Our primary predictor was device type.</p>
<pre class="r"><code>mod.responseD = lmer(response~devicetype + (1|proid), 
                  data = items_12)
anova(mod.responseD)</code></pre>
<pre><code>## Type III Analysis of Variance Table with Satterthwaite&#39;s method
##            Sum Sq Mean Sq NumDF DenDF F value Pr(&gt;F)
## devicetype 2.9109  1.4554     2    32  0.9685 0.3905</code></pre>
<p>When examining both Block 1 and Block 2 data, device type was unassociated with the time it took to respond to personality items <span class="math inline">\((F(2, 32.00) = 0.97, p = .391)\)</span>.</p>
<pre class="r"><code>plot1 = plot_model(mod.responseD, type = &quot;pred&quot;) 

plot1$devicetype +
  labs(x = NULL,
       y = &quot;Expected response&quot;,
       title = &quot;Expected responses by device&quot;,
       caption = &quot;Bars represent 95% confidence intervals&quot;) +
  theme_pubclean()</code></pre>
<div class="figure"><span style="display:block;" id="fig:device-14"></span>
<img src="device_files/figure-html/device-14-1.png" alt="Predicted response on personality items by condition." width="672" />
<p class="caption">
Figure 5: Predicted response on personality items by condition.
</p>
</div>
<pre class="r"><code>means_by_group = items_12 %&gt;%
  group_by(devicetype) %&gt;% 
  summarise(m = mean(response),
            s = sd(response))

items_12 %&gt;%
  ggplot(aes(x = response)) +
  geom_histogram(aes(fill = block),
                 position = &quot;dodge&quot;,
                 bins = 6, color = &quot;white&quot;) +
  geom_vline(aes(xintercept = m), 
             data = means_by_group) +
  facet_wrap(~devicetype, scales = &quot;free_y&quot;) +
  #guides(fill = &quot;none&quot;) +
  scale_x_continuous(breaks = 1:6) +
  labs(y = &quot;Number of particpants&quot;,
       title = &quot;Distribution of responses by format&quot;) +
  theme_pubr()</code></pre>
<div class="figure"><span style="display:block;" id="fig:device-15"></span>
<img src="device_files/figure-html/device-15-1.png" alt="Distribution of responses by category" width="672" />
<p class="caption">
Figure 6: Distribution of responses by category
</p>
</div>
</div>
<div id="device-by-format-1" class="section level3" number="0.3.2">
<h3><span class="header-section-number">0.3.2</span> Device by format</h3>
<p>We also check whether item format moderated the relationship between device type and response.</p>
<pre class="r"><code>mod.responseD2 = lmer(response~devicetype*format + (1|proid), 
                  data = items_12)
anova(mod.responseD2)</code></pre>
<pre><code>## Type III Analysis of Variance Table with Satterthwaite&#39;s method
##                    Sum Sq Mean Sq NumDF   DenDF F value Pr(&gt;F)
## devicetype         1.8061 0.90304     2   32.83  0.6016 0.5539
## format             5.1709 1.72363     3 2105.79  1.1483 0.3283
## devicetype:format 13.6298 2.27163     6 2102.81  1.5133 0.1697</code></pre>
<p>The interaction between device type and format was unassociated with the time it took to respond to personality items <span class="math inline">\((F(6, 2,102.81) = 1.51, p = .170)\)</span>.</p>
<pre class="r"><code>plot2 = plot_model(mod.responseD2, type = &quot;pred&quot;, terms = c(&quot;format&quot;, &quot;devicetype&quot;)) 

plot2 +
  geom_line() +
  labs(x = NULL,
       y = &quot;Average response&quot;,
       title = &quot;Average responses by device&quot;,
       caption = &quot;Bars represent 95% confidence intervals&quot;) +
  theme_pubclean()</code></pre>
<div class="figure"><span style="display:block;" id="fig:device-18"></span>
<img src="device_files/figure-html/device-18-1.png" alt="Predicted response on personality items by condition." width="672" />
<p class="caption">
Figure 7: Predicted response on personality items by condition.
</p>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
