<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Does item format impact response syle?</title>

<script src="site_libs/header-attrs-2.20/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">On item wording effects</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="1-cleaning.html">Data cleaning</a>
</li>
<li>
  <a href="descriptives.html">Descriptives</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Analysis
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="response_style.html">Does item formatting affect response style?</a>
    </li>
    <li>
      <a href="internal.html">Does item formatting affect internal consistency?</a>
    </li>
    <li>
      <a href="test_retest.html">Does item formatting affect test-retest reliability?</a>
    </li>
    <li>
      <a href="timing_format.html">Does timing differ across format?</a>
    </li>
    <li>
      <a href="device.html">Does device type affect response and timing?</a>
    </li>
  </ul>
</li>
<li>
  <a href="power.html">Power analysis</a>
</li>
<li>
  <a href="workspace.html">R version and packages</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/pie-lab/wording-effects">
    <span class="fa fa-github"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Does item format impact response syle?</h1>
<h4 class="date">Last updated 2023-04-20</h4>

</div>


<p>The primary aims of this study are to evaluate the effects of item
wording in online, self-report personality assessment. Specifically, we
intend to consider the extent to which incremental wording changes may
influence differences in participant response style. These wording
changes will include a progression from using (1) trait-descriptive
adjectives by themselves, (2) with the linking verb “to be” (Am…), (3)
with the additional verb “to tend” (Tend to be…), and (4) with the
pronoun “someone” (Am someone who tends to be…).</p>
<p>In this section, we test the impact of item format on three
components of response style:</p>
<ol style="list-style-type: decimal">
<li>Expected (average) response</li>
<li>Likelihood of extreme responding</li>
<li>Nay-saying</li>
</ol>
<p>For these analyses, we use data from Blocks 1 and 2.</p>
<div id="expected-response" class="section level2">
<h2>Expected response</h2>
<p>We used a multilevel model. Our primary predictor was format. We use
data from all three blocks; as a consequence, each person contributes
either two or three data points for each of the trait descriptive
adjectives. Thus, we nest responses within participant to account for
this dependency. This is equivalent to a repeated measures ANOVA.
However, in this omnibus model, we include responses to all trait
adjectives. Thus, we must also account for adjective-specific
contributions to variability. Finally, we include a random term for
block. This is not hypothesized to account for significant variability,
but we include this term in the event that block contributes
significantly to ratings.</p>
<p>We use the <code>aov</code> function to calculate the amount of
variability in response due to format.</p>
<pre class="r"><code>mod.expected = items_df %&gt;% 
  filter(block %in% c(1,2)) %&gt;% 
  filter(!(item %in% bfmm)) %&gt;% 
  glmmTMB(response~format + (1|item) + (1|proid) + (1|block), 
                  data = .)

tidy(aov(mod.expected))</code></pre>
<pre><code>## # A tibble: 5 × 6
##   term         df    sumsq meansq statistic      p.value
##   &lt;chr&gt;     &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;        &lt;dbl&gt;
## 1 format        3    40.4   13.5      11.1   0.000000290
## 2 item         30 17934.   598.      492.    0          
## 3 proid       973 21077.    21.7      17.8   0          
## 4 block         1     3.18   3.18      2.62  0.106      
## 5 Residuals 59380 72129.     1.21     NA    NA</code></pre>
<p>Item format was associated with participants’ expected responses to
personality items <span class="math inline">\((F(3.00, 59,380.00) =
11.08, p = &lt; .001)\)</span>. See Figure @ref(fig:responsestyle7) for
a visualization of this effect. In addition, Figure
@ref(fig:responsestyle8) shows the full distribution of responses across
format.</p>
<div class="figure">
<img src="response_style_files/figure-html/responsestyle7-1.png" alt="Predicted response on personality items by condition." width="672" />
<p class="caption">
Predicted response on personality items by condition.
</p>
</div>
<div class="figure">
<img src="response_style_files/figure-html/responsestyle8-1.png" alt="Distribution of responses by category." width="672" />
<p class="caption">
Distribution of responses by category.
</p>
</div>
<div id="one-model-for-each-adjective" class="section level3">
<h3>One model for each adjective</h3>
<p>We repeat this analysis separately for each trait.</p>
<pre class="r"><code>mod_by_item = items_df %&gt;%
  filter(block %in% c(1,2)) %&gt;% 
  filter(!(item %in% bfmm)) %&gt;% 
  group_by(item) %&gt;%
  nest() %&gt;%
  mutate(mod = map(data, ~glmmTMB(response~format + (1|proid) + (1|block), 
                                  data = .))) %&gt;%
  mutate(aov = map(mod, aov))</code></pre>
<p>We apply a Holm correction to the <em>p</em>-values extracted from
these analyses, to adjust for the number of tests conducted. We present
results in Table @ref(tab:responsestyle10), which is organized by
whether items were reverse-coded prior to analysis.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
Format effects on expected response by item.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Item
</th>
<th style="text-align:center;">
Reverse Scored?
</th>
<th style="text-align:center;">
SS
</th>
<th style="text-align:center;">
MS
</th>
<th style="text-align:center;">
df1
</th>
<th style="text-align:center;">
df2
</th>
<th style="text-align:center;">
F
</th>
<th style="text-align:right;">
raw
</th>
<th style="text-align:right;">
adj
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
active
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
9.86
</td>
<td style="text-align:center;">
3.29
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
14.36
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
&lt; .001
</td>
</tr>
<tr>
<td style="text-align:left;">
adventurous
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
3.87
</td>
<td style="text-align:center;">
1.29
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
5.16
</td>
<td style="text-align:right;">
.002
</td>
<td style="text-align:right;">
.022
</td>
</tr>
<tr>
<td style="text-align:left;">
broadminded
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
8.83
</td>
<td style="text-align:center;">
2.94
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
12.87
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
&lt; .001
</td>
</tr>
<tr>
<td style="text-align:left;">
calm
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
9.05
</td>
<td style="text-align:center;">
3.02
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
9.14
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
&lt; .001
</td>
</tr>
<tr>
<td style="text-align:left;">
caring
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
6.56
</td>
<td style="text-align:center;">
2.19
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
9.93
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
&lt; .001
</td>
</tr>
<tr>
<td style="text-align:left;">
cautious
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
1.21
</td>
<td style="text-align:center;">
0.40
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
1.08
</td>
<td style="text-align:right;">
.357
</td>
<td style="text-align:right;">
.713
</td>
</tr>
<tr>
<td style="text-align:left;">
creative
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
2.36
</td>
<td style="text-align:center;">
0.79
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
4.14
</td>
<td style="text-align:right;">
.006
</td>
<td style="text-align:right;">
.063
</td>
</tr>
<tr>
<td style="text-align:left;">
curious
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
3.46
</td>
<td style="text-align:center;">
1.15
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
4.91
</td>
<td style="text-align:right;">
.002
</td>
<td style="text-align:right;">
.026
</td>
</tr>
<tr>
<td style="text-align:left;">
friendly
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
3.06
</td>
<td style="text-align:center;">
1.02
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
5.21
</td>
<td style="text-align:right;">
.001
</td>
<td style="text-align:right;">
.022
</td>
</tr>
<tr>
<td style="text-align:left;">
hardworking
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
6.74
</td>
<td style="text-align:center;">
2.25
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
11.12
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
&lt; .001
</td>
</tr>
<tr>
<td style="text-align:left;">
helpful
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
2.48
</td>
<td style="text-align:center;">
0.83
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
4.56
</td>
<td style="text-align:right;">
.004
</td>
<td style="text-align:right;">
.039
</td>
</tr>
<tr>
<td style="text-align:left;">
imaginative
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
3.35
</td>
<td style="text-align:center;">
1.12
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
5.18
</td>
<td style="text-align:right;">
.001
</td>
<td style="text-align:right;">
.022
</td>
</tr>
<tr>
<td style="text-align:left;">
intelligent
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
1.00
</td>
<td style="text-align:center;">
0.33
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
2.53
</td>
<td style="text-align:right;">
.056
</td>
<td style="text-align:right;">
.225
</td>
</tr>
<tr>
<td style="text-align:left;">
lively
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
9.42
</td>
<td style="text-align:center;">
3.14
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
10.41
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
&lt; .001
</td>
</tr>
<tr>
<td style="text-align:left;">
organized
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.41
</td>
<td style="text-align:center;">
0.14
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
0.61
</td>
<td style="text-align:right;">
.608
</td>
<td style="text-align:right;">
.713
</td>
</tr>
<tr>
<td style="text-align:left;">
outgoing
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
12.84
</td>
<td style="text-align:center;">
4.28
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
15.89
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
&lt; .001
</td>
</tr>
<tr>
<td style="text-align:left;">
responsible
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
8.66
</td>
<td style="text-align:center;">
2.89
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
14.27
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
&lt; .001
</td>
</tr>
<tr>
<td style="text-align:left;">
selfdisciplined
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
7.70
</td>
<td style="text-align:center;">
2.57
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
10.76
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
&lt; .001
</td>
</tr>
<tr>
<td style="text-align:left;">
softhearted
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
1.82
</td>
<td style="text-align:center;">
0.61
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
2.77
</td>
<td style="text-align:right;">
.041
</td>
<td style="text-align:right;">
.204
</td>
</tr>
<tr>
<td style="text-align:left;">
sophisticated
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
2.65
</td>
<td style="text-align:center;">
0.88
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
2.93
</td>
<td style="text-align:right;">
.033
</td>
<td style="text-align:right;">
.195
</td>
</tr>
<tr>
<td style="text-align:left;">
sympathetic
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
4.01
</td>
<td style="text-align:center;">
1.34
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
6.01
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
.008
</td>
</tr>
<tr>
<td style="text-align:left;">
talkative
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
6.99
</td>
<td style="text-align:center;">
2.33
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
5.66
</td>
<td style="text-align:right;">
.001
</td>
<td style="text-align:right;">
.012
</td>
</tr>
<tr>
<td style="text-align:left;">
thorough
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
1.47
</td>
<td style="text-align:center;">
0.49
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
2.15
</td>
<td style="text-align:right;">
.092
</td>
<td style="text-align:right;">
.276
</td>
</tr>
<tr>
<td style="text-align:left;">
thrifty
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
3.09
</td>
<td style="text-align:center;">
1.03
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
3.53
</td>
<td style="text-align:right;">
.015
</td>
<td style="text-align:right;">
.131
</td>
</tr>
<tr>
<td style="text-align:left;">
warm
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
4.56
</td>
<td style="text-align:center;">
1.52
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
8.31
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
&lt; .001
</td>
</tr>
<tr>
<td style="text-align:left;">
careless
</td>
<td style="text-align:center;">
Y
</td>
<td style="text-align:center;">
4.76
</td>
<td style="text-align:center;">
1.59
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
3.44
</td>
<td style="text-align:right;">
.016
</td>
<td style="text-align:right;">
.132
</td>
</tr>
<tr>
<td style="text-align:left;">
impulsive
</td>
<td style="text-align:center;">
Y
</td>
<td style="text-align:center;">
7.42
</td>
<td style="text-align:center;">
2.47
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
6.65
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
.003
</td>
</tr>
<tr>
<td style="text-align:left;">
moody
</td>
<td style="text-align:center;">
Y
</td>
<td style="text-align:center;">
2.33
</td>
<td style="text-align:center;">
0.78
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
3.39
</td>
<td style="text-align:right;">
.018
</td>
<td style="text-align:right;">
.132
</td>
</tr>
<tr>
<td style="text-align:left;">
nervous
</td>
<td style="text-align:center;">
Y
</td>
<td style="text-align:center;">
15.02
</td>
<td style="text-align:center;">
5.01
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
14.83
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
&lt; .001
</td>
</tr>
<tr>
<td style="text-align:left;">
reckless
</td>
<td style="text-align:center;">
Y
</td>
<td style="text-align:center;">
16.70
</td>
<td style="text-align:center;">
5.57
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
18.61
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
&lt; .001
</td>
</tr>
<tr>
<td style="text-align:left;">
worrying
</td>
<td style="text-align:center;">
Y
</td>
<td style="text-align:center;">
14.29
</td>
<td style="text-align:center;">
4.76
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
14.38
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
&lt; .001
</td>
</tr>
</tbody>
</table>
</div>
<div id="pairwise-t-tests-for-significant-anovas"
class="section level3">
<h3>Pairwise t-tests for significant ANOVAs</h3>
<p>When format was a significant predictor of expected response for an
item (using the un-adjusted <em>p</em>-value here), we follow up with
pairwise comparisons of format. Here we identify the items which meet
this criteria. In the manuscript proper, we will only report the results
for items in which format was significant, even after applying the Holm
correction.</p>
<p>Differences in means and significance are shown in Table
@ref(tab:responsestyle12). These are also plotted in Figure
@ref(fig:responsestyle13).</p>
<pre class="r"><code>sig_item = summary_by_item %&gt;%
  filter(p.value &lt; .05)

sig_item = sig_item$item
sig_item</code></pre>
<pre><code>##  [1] &quot;outgoing&quot;        &quot;helpful&quot;         &quot;reckless&quot;        &quot;moody&quot;          
##  [5] &quot;friendly&quot;        &quot;warm&quot;            &quot;worrying&quot;        &quot;responsible&quot;    
##  [9] &quot;lively&quot;          &quot;caring&quot;          &quot;nervous&quot;         &quot;creative&quot;       
## [13] &quot;hardworking&quot;     &quot;imaginative&quot;     &quot;softhearted&quot;     &quot;calm&quot;           
## [17] &quot;selfdisciplined&quot; &quot;curious&quot;         &quot;active&quot;          &quot;careless&quot;       
## [21] &quot;broadminded&quot;     &quot;impulsive&quot;       &quot;sympathetic&quot;     &quot;talkative&quot;      
## [25] &quot;sophisticated&quot;   &quot;adventurous&quot;     &quot;thrifty&quot;</code></pre>
<pre class="r"><code>pairwise_response = mod_by_item %&gt;% 
  #only significant items
  filter(item %in% sig_item) %&gt;% 
  #use emmeans package to calculate format means and run pairwise comparisons
  mutate(comp = map(mod, emmeans, pairwise~format, adjust = &quot;none&quot;),
         means = map(comp, &quot;emmeans&quot;),
         means = map(means, as.data.frame),
         contrasts = map(comp, &quot;contrasts&quot;),
         contrasts = map(contrasts, as.data.frame))</code></pre>
<pre class="r"><code>pairwise_response %&gt;% 
  select(item, contrasts) %&gt;% 
  unnest(cols = c(contrasts)) %&gt;% 
  mutate(estimate = printnum(estimate),
         estimate = case_when(
           p.value &lt; .001 ~ paste0(estimate, &quot;***&quot;),
           p.value &lt; .01 ~ paste0(estimate, &quot;**&quot;),
           p.value &lt; .05 ~ paste0(estimate, &quot;*&quot;),
           TRUE ~ estimate
         )) %&gt;% 
  mutate(
    contrast = str_replace(contrast, &quot;Adjective\nOnly&quot;, &quot;A&quot;),
    contrast = str_replace(contrast, &quot;Am\nAdjective&quot;, &quot;B&quot;),
    contrast = str_replace(contrast, &quot;Tend to be\nAdjective&quot;, &quot;C&quot;),
    contrast = str_replace(contrast, &quot;Am someone\nwho tends to be\nAdjective&quot;, &quot;D&quot;),
    contrast = str_remove_all(contrast, &quot; &quot;)
  ) %&gt;% 
  select(item, contrast, estimate) %&gt;% 
  pivot_wider(names_from = contrast, values_from = estimate) %&gt;% 
  kable(booktabs = T,
        caption = &quot;Pairwise differences of means by format. A = Adjective only. B = Am Adjective. C = Tend to be Adjective. D = Am someone who tends to be Adjective. * p &lt; .05, ** p &lt; .01, *** p &lt; .001&quot;) %&gt;%
  kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
Pairwise differences of means by format. A = Adjective only. B = Am
Adjective. C = Tend to be Adjective. D = Am someone who tends to be
Adjective. * p
</caption>
<thead>
<tr>
<th style="text-align:left;">
item
</th>
<th style="text-align:left;">
A-B
</th>
<th style="text-align:left;">
A-C
</th>
<th style="text-align:left;">
A-D
</th>
<th style="text-align:left;">
B-C
</th>
<th style="text-align:left;">
B-D
</th>
<th style="text-align:left;">
C-D
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
outgoing
</td>
<td style="text-align:left;">
0.02
</td>
<td style="text-align:left;">
0.10*
</td>
<td style="text-align:left;">
0.09*
</td>
<td style="text-align:left;">
0.08
</td>
<td style="text-align:left;">
0.08
</td>
<td style="text-align:left;">
0.00
</td>
</tr>
<tr>
<td style="text-align:left;">
helpful
</td>
<td style="text-align:left;">
-0.02
</td>
<td style="text-align:left;">
-0.07
</td>
<td style="text-align:left;">
-0.04
</td>
<td style="text-align:left;">
-0.05
</td>
<td style="text-align:left;">
-0.02
</td>
<td style="text-align:left;">
0.03
</td>
</tr>
<tr>
<td style="text-align:left;">
reckless
</td>
<td style="text-align:left;">
0.01
</td>
<td style="text-align:left;">
0.08
</td>
<td style="text-align:left;">
0.00
</td>
<td style="text-align:left;">
0.07
</td>
<td style="text-align:left;">
-0.01
</td>
<td style="text-align:left;">
-0.08
</td>
</tr>
<tr>
<td style="text-align:left;">
moody
</td>
<td style="text-align:left;">
-0.06
</td>
<td style="text-align:left;">
0.01
</td>
<td style="text-align:left;">
-0.02
</td>
<td style="text-align:left;">
0.07
</td>
<td style="text-align:left;">
0.03
</td>
<td style="text-align:left;">
-0.04
</td>
</tr>
<tr>
<td style="text-align:left;">
friendly
</td>
<td style="text-align:left;">
0.01
</td>
<td style="text-align:left;">
0.02
</td>
<td style="text-align:left;">
0.00
</td>
<td style="text-align:left;">
0.01
</td>
<td style="text-align:left;">
-0.01
</td>
<td style="text-align:left;">
-0.02
</td>
</tr>
<tr>
<td style="text-align:left;">
warm
</td>
<td style="text-align:left;">
0.02
</td>
<td style="text-align:left;">
0.02
</td>
<td style="text-align:left;">
0.01
</td>
<td style="text-align:left;">
-0.01
</td>
<td style="text-align:left;">
-0.02
</td>
<td style="text-align:left;">
-0.01
</td>
</tr>
<tr>
<td style="text-align:left;">
worrying
</td>
<td style="text-align:left;">
-0.04
</td>
<td style="text-align:left;">
-0.02
</td>
<td style="text-align:left;">
0.04
</td>
<td style="text-align:left;">
0.02
</td>
<td style="text-align:left;">
0.08
</td>
<td style="text-align:left;">
0.05
</td>
</tr>
<tr>
<td style="text-align:left;">
responsible
</td>
<td style="text-align:left;">
0.00
</td>
<td style="text-align:left;">
0.00
</td>
<td style="text-align:left;">
0.12**
</td>
<td style="text-align:left;">
0.00
</td>
<td style="text-align:left;">
0.12**
</td>
<td style="text-align:left;">
0.12**
</td>
</tr>
<tr>
<td style="text-align:left;">
lively
</td>
<td style="text-align:left;">
-0.08
</td>
<td style="text-align:left;">
0.05
</td>
<td style="text-align:left;">
0.10*
</td>
<td style="text-align:left;">
0.14**
</td>
<td style="text-align:left;">
0.18***
</td>
<td style="text-align:left;">
0.04
</td>
</tr>
<tr>
<td style="text-align:left;">
caring
</td>
<td style="text-align:left;">
-0.06
</td>
<td style="text-align:left;">
0.02
</td>
<td style="text-align:left;">
0.00
</td>
<td style="text-align:left;">
0.08
</td>
<td style="text-align:left;">
0.05
</td>
<td style="text-align:left;">
-0.02
</td>
</tr>
<tr>
<td style="text-align:left;">
nervous
</td>
<td style="text-align:left;">
0.07
</td>
<td style="text-align:left;">
0.08
</td>
<td style="text-align:left;">
0.11*
</td>
<td style="text-align:left;">
0.02
</td>
<td style="text-align:left;">
0.04
</td>
<td style="text-align:left;">
0.03
</td>
</tr>
<tr>
<td style="text-align:left;">
creative
</td>
<td style="text-align:left;">
0.00
</td>
<td style="text-align:left;">
0.06
</td>
<td style="text-align:left;">
0.06
</td>
<td style="text-align:left;">
0.06
</td>
<td style="text-align:left;">
0.06
</td>
<td style="text-align:left;">
0.00
</td>
</tr>
<tr>
<td style="text-align:left;">
hardworking
</td>
<td style="text-align:left;">
-0.04
</td>
<td style="text-align:left;">
0.02
</td>
<td style="text-align:left;">
0.03
</td>
<td style="text-align:left;">
0.06
</td>
<td style="text-align:left;">
0.07
</td>
<td style="text-align:left;">
0.01
</td>
</tr>
<tr>
<td style="text-align:left;">
imaginative
</td>
<td style="text-align:left;">
-0.04
</td>
<td style="text-align:left;">
-0.04
</td>
<td style="text-align:left;">
-0.01
</td>
<td style="text-align:left;">
0.00
</td>
<td style="text-align:left;">
0.03
</td>
<td style="text-align:left;">
0.03
</td>
</tr>
<tr>
<td style="text-align:left;">
softhearted
</td>
<td style="text-align:left;">
-0.05
</td>
<td style="text-align:left;">
-0.03
</td>
<td style="text-align:left;">
-0.02
</td>
<td style="text-align:left;">
0.01
</td>
<td style="text-align:left;">
0.03
</td>
<td style="text-align:left;">
0.02
</td>
</tr>
<tr>
<td style="text-align:left;">
calm
</td>
<td style="text-align:left;">
0.07
</td>
<td style="text-align:left;">
0.02
</td>
<td style="text-align:left;">
0.11*
</td>
<td style="text-align:left;">
-0.05
</td>
<td style="text-align:left;">
0.04
</td>
<td style="text-align:left;">
0.09
</td>
</tr>
<tr>
<td style="text-align:left;">
selfdisciplined
</td>
<td style="text-align:left;">
0.01
</td>
<td style="text-align:left;">
0.01
</td>
<td style="text-align:left;">
0.10*
</td>
<td style="text-align:left;">
0.01
</td>
<td style="text-align:left;">
0.10*
</td>
<td style="text-align:left;">
0.09*
</td>
</tr>
<tr>
<td style="text-align:left;">
curious
</td>
<td style="text-align:left;">
-0.05
</td>
<td style="text-align:left;">
-0.01
</td>
<td style="text-align:left;">
0.01
</td>
<td style="text-align:left;">
0.04
</td>
<td style="text-align:left;">
0.06
</td>
<td style="text-align:left;">
0.02
</td>
</tr>
<tr>
<td style="text-align:left;">
active
</td>
<td style="text-align:left;">
-0.01
</td>
<td style="text-align:left;">
0.01
</td>
<td style="text-align:left;">
0.04
</td>
<td style="text-align:left;">
0.02
</td>
<td style="text-align:left;">
0.05
</td>
<td style="text-align:left;">
0.03
</td>
</tr>
<tr>
<td style="text-align:left;">
careless
</td>
<td style="text-align:left;">
0.03
</td>
<td style="text-align:left;">
0.02
</td>
<td style="text-align:left;">
-0.03
</td>
<td style="text-align:left;">
-0.01
</td>
<td style="text-align:left;">
-0.06
</td>
<td style="text-align:left;">
-0.05
</td>
</tr>
<tr>
<td style="text-align:left;">
broadminded
</td>
<td style="text-align:left;">
-0.04
</td>
<td style="text-align:left;">
-0.03
</td>
<td style="text-align:left;">
-0.04
</td>
<td style="text-align:left;">
0.01
</td>
<td style="text-align:left;">
0.00
</td>
<td style="text-align:left;">
-0.01
</td>
</tr>
<tr>
<td style="text-align:left;">
impulsive
</td>
<td style="text-align:left;">
-0.10
</td>
<td style="text-align:left;">
-0.14**
</td>
<td style="text-align:left;">
-0.08
</td>
<td style="text-align:left;">
-0.04
</td>
<td style="text-align:left;">
0.02
</td>
<td style="text-align:left;">
0.05
</td>
</tr>
<tr>
<td style="text-align:left;">
sympathetic
</td>
<td style="text-align:left;">
0.00
</td>
<td style="text-align:left;">
0.01
</td>
<td style="text-align:left;">
-0.04
</td>
<td style="text-align:left;">
0.01
</td>
<td style="text-align:left;">
-0.05
</td>
<td style="text-align:left;">
-0.05
</td>
</tr>
<tr>
<td style="text-align:left;">
talkative
</td>
<td style="text-align:left;">
-0.07
</td>
<td style="text-align:left;">
-0.01
</td>
<td style="text-align:left;">
0.01
</td>
<td style="text-align:left;">
0.06
</td>
<td style="text-align:left;">
0.08
</td>
<td style="text-align:left;">
0.02
</td>
</tr>
<tr>
<td style="text-align:left;">
sophisticated
</td>
<td style="text-align:left;">
-0.04
</td>
<td style="text-align:left;">
0.00
</td>
<td style="text-align:left;">
0.01
</td>
<td style="text-align:left;">
0.04
</td>
<td style="text-align:left;">
0.05
</td>
<td style="text-align:left;">
0.01
</td>
</tr>
<tr>
<td style="text-align:left;">
adventurous
</td>
<td style="text-align:left;">
0.00
</td>
<td style="text-align:left;">
0.05
</td>
<td style="text-align:left;">
0.05
</td>
<td style="text-align:left;">
0.05
</td>
<td style="text-align:left;">
0.05
</td>
<td style="text-align:left;">
0.01
</td>
</tr>
<tr>
<td style="text-align:left;">
thrifty
</td>
<td style="text-align:left;">
-0.02
</td>
<td style="text-align:left;">
0.00
</td>
<td style="text-align:left;">
-0.02
</td>
<td style="text-align:left;">
0.03
</td>
<td style="text-align:left;">
0.01
</td>
<td style="text-align:left;">
-0.02
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>pairwise_response %&gt;% 
  select(item, means) %&gt;% 
  unnest(cols = c(means)) %&gt;% 
  mutate(format = case_when(
    format == &quot;Adjective\nOnly&quot; ~ 1,
    format == &quot;Am\nAdjective&quot; ~ 2,
    format == &quot;Tend to be\nAdjective&quot; ~ 3,
    format == &quot;Am someone\nwho tends to be\nAdjective&quot; ~ 4)) %&gt;% 
  ggplot(aes(x = format, y = emmean)) +
  geom_point(stat = &quot;identity&quot;) + 
  geom_line(alpha = .3) +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = .3) +
  scale_x_continuous(breaks = c(1:4), labels= c(&quot;A&quot;,&quot;B&quot;,&quot;C&quot;,&quot;D&quot;)) +
  labs(x = NULL, y = &quot;Expected response&quot;) +
  facet_wrap(~item) +
  theme_pubr() </code></pre>
<div class="figure">
<img src="response_style_files/figure-html/responsestyle13-1.png" alt="Expected means by format and item. These items were significantly affected by response. A = Adjective only. B = Am Adjective. C = Tend to be Adjective. D = Am someone who tends to be Adjective." width="672" />
<p class="caption">
Expected means by format and item. These items were significantly
affected by response. A = Adjective only. B = Am Adjective. C = Tend to
be Adjective. D = Am someone who tends to be Adjective.
</p>
</div>
</div>
</div>
<div id="extreme-responding" class="section level2">
<h2>Extreme responding</h2>
<p>We define <em>extreme responding</em> as answering either a 1 (Very
inaccurate) or a 6 (Very accurate). To model likelihood of extreme
responding by format, we use logistic regression.</p>
<pre class="r"><code>items_df = items_df %&gt;% 
  mutate(extreme = case_when(
    response == 1 ~ 1,
    response == 6 ~ 1,
    TRUE ~ 0
  ))</code></pre>
<pre class="r"><code>mod.extreme = items_df %&gt;% 
  filter(block %in% c(1,2)) %&gt;% 
  filter(!(item %in% bfmm)) %&gt;% 
  glmmTMB(extreme~format + (1|proid) + (1|item) + (1|block), 
          data = ., 
          family = &quot;binomial&quot;)
tidy(aov(mod.extreme))</code></pre>
<pre><code>## # A tibble: 5 × 6
##   term         df   sumsq meansq statistic    p.value
##   &lt;chr&gt;     &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
## 1 format        3    3.36  1.12       7.48  5.32e-  5
## 2 proid       973 2895.    2.98      19.8   0        
## 3 item         30  243.    8.10      54.1   1.33e-318
## 4 block         1    1.99  1.99      13.3   2.73e-  4
## 5 Residuals 59380 8900.    0.150     NA    NA</code></pre>
<p>Item format was associated with participants’ expected responses to
personality items <span class="math inline">\((F(3.00, 59,380.00) =
7.48, p = &lt; .001)\)</span>. See Figure @ref(fig:responsestyle17) for
a visualization of this effect.</p>
<div class="figure">
<img src="response_style_files/figure-html/responsestyle17-1.png" alt="Predicted response on personality items by condition." width="672" />
<p class="caption">
Predicted response on personality items by condition.
</p>
</div>
<div id="one-model-for-each-adjective-1" class="section level3">
<h3>One model for each adjective</h3>
<p>We repeat this analysis separately for each trait.</p>
<pre class="r"><code>mod_by_item_ex = items_df %&gt;%
  filter(block %in% c(1,2)) %&gt;%
  filter(!(item %in% bfmm)) %&gt;% 
  group_by(item) %&gt;%
  nest() %&gt;%
  mutate(mod = map(data, ~glmmTMB(extreme~format + (1|proid) + (1|block), 
                                  data = .,
                                  family = &quot;binomial&quot;))) %&gt;%
  mutate(aov = map(mod, aov))</code></pre>
<p>We apply a Holm correction to the <em>p</em>-values extracted from
these analyses, to adjust for the number of tests conducted. We present
results in Table @ref(tab:responsestyle19), which is organized by
whether items were reverse-coded prior to analysis.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
Format effects on extrene response by item.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Item
</th>
<th style="text-align:center;">
Reverse Scored?
</th>
<th style="text-align:center;">
SS
</th>
<th style="text-align:center;">
MS
</th>
<th style="text-align:center;">
df
</th>
<th style="text-align:center;">
df2
</th>
<th style="text-align:center;">
F
</th>
<th style="text-align:right;">
raw
</th>
<th style="text-align:right;">
adj
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
active
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.50
</td>
<td style="text-align:center;">
0.17
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
4.37
</td>
<td style="text-align:right;">
.005
</td>
<td style="text-align:right;">
.087
</td>
</tr>
<tr>
<td style="text-align:left;">
adventurous
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.55
</td>
<td style="text-align:center;">
0.18
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
3.65
</td>
<td style="text-align:right;">
.012
</td>
<td style="text-align:right;">
.208
</td>
</tr>
<tr>
<td style="text-align:left;">
broadminded
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.93
</td>
<td style="text-align:center;">
0.31
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
6.44
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
.006
</td>
</tr>
<tr>
<td style="text-align:left;">
calm
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.09
</td>
<td style="text-align:center;">
0.03
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
0.50
</td>
<td style="text-align:right;">
.679
</td>
<td style="text-align:right;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
caring
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
1.91
</td>
<td style="text-align:center;">
0.64
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
10.29
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
&lt; .001
</td>
</tr>
<tr>
<td style="text-align:left;">
cautious
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.11
</td>
<td style="text-align:center;">
0.04
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
0.58
</td>
<td style="text-align:right;">
.630
</td>
<td style="text-align:right;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
creative
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
1.14
</td>
<td style="text-align:center;">
0.38
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
7.86
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
.001
</td>
</tr>
<tr>
<td style="text-align:left;">
curious
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.46
</td>
<td style="text-align:center;">
0.15
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
2.67
</td>
<td style="text-align:right;">
.047
</td>
<td style="text-align:right;">
.695
</td>
</tr>
<tr>
<td style="text-align:left;">
friendly
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.69
</td>
<td style="text-align:center;">
0.23
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
3.63
</td>
<td style="text-align:right;">
.013
</td>
<td style="text-align:right;">
.208
</td>
</tr>
<tr>
<td style="text-align:left;">
hardworking
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.45
</td>
<td style="text-align:center;">
0.15
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
2.67
</td>
<td style="text-align:right;">
.046
</td>
<td style="text-align:right;">
.695
</td>
</tr>
<tr>
<td style="text-align:left;">
helpful
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.91
</td>
<td style="text-align:center;">
0.30
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
5.01
</td>
<td style="text-align:right;">
.002
</td>
<td style="text-align:right;">
.038
</td>
</tr>
<tr>
<td style="text-align:left;">
imaginative
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
1.15
</td>
<td style="text-align:center;">
0.38
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
6.87
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
.004
</td>
</tr>
<tr>
<td style="text-align:left;">
intelligent
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.97
</td>
<td style="text-align:center;">
0.32
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
6.72
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
.004
</td>
</tr>
<tr>
<td style="text-align:left;">
lively
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.16
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
1.08
</td>
<td style="text-align:right;">
.355
</td>
<td style="text-align:right;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
organized
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.08
</td>
<td style="text-align:center;">
0.03
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
0.58
</td>
<td style="text-align:right;">
.627
</td>
<td style="text-align:right;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
outgoing
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
0.02
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
0.41
</td>
<td style="text-align:right;">
.746
</td>
<td style="text-align:right;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
responsible
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.37
</td>
<td style="text-align:center;">
0.12
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
1.93
</td>
<td style="text-align:right;">
.123
</td>
<td style="text-align:right;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
selfdisciplined
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.46
</td>
<td style="text-align:center;">
0.15
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
2.50
</td>
<td style="text-align:right;">
.059
</td>
<td style="text-align:right;">
.761
</td>
</tr>
<tr>
<td style="text-align:left;">
softhearted
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.40
</td>
<td style="text-align:center;">
0.13
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
2.03
</td>
<td style="text-align:right;">
.108
</td>
<td style="text-align:right;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
sophisticated
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.02
</td>
<td style="text-align:center;">
0.01
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
0.12
</td>
<td style="text-align:right;">
.951
</td>
<td style="text-align:right;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
sympathetic
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
1.03
</td>
<td style="text-align:center;">
0.34
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
6.13
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
.009
</td>
</tr>
<tr>
<td style="text-align:left;">
talkative
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.85
</td>
<td style="text-align:center;">
0.28
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
5.12
</td>
<td style="text-align:right;">
.002
</td>
<td style="text-align:right;">
.034
</td>
</tr>
<tr>
<td style="text-align:left;">
thorough
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.39
</td>
<td style="text-align:center;">
0.13
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
2.41
</td>
<td style="text-align:right;">
.066
</td>
<td style="text-align:right;">
.787
</td>
</tr>
<tr>
<td style="text-align:left;">
thrifty
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.14
</td>
<td style="text-align:center;">
0.05
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
1.12
</td>
<td style="text-align:right;">
.340
</td>
<td style="text-align:right;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
warm
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.77
</td>
<td style="text-align:center;">
0.26
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
5.65
</td>
<td style="text-align:right;">
.001
</td>
<td style="text-align:right;">
.017
</td>
</tr>
<tr>
<td style="text-align:left;">
careless
</td>
<td style="text-align:center;">
Y
</td>
<td style="text-align:center;">
0.77
</td>
<td style="text-align:center;">
0.26
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
3.71
</td>
<td style="text-align:right;">
.011
</td>
<td style="text-align:right;">
.205
</td>
</tr>
<tr>
<td style="text-align:left;">
impulsive
</td>
<td style="text-align:center;">
Y
</td>
<td style="text-align:center;">
1.36
</td>
<td style="text-align:center;">
0.45
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
7.09
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
.003
</td>
</tr>
<tr>
<td style="text-align:left;">
moody
</td>
<td style="text-align:center;">
Y
</td>
<td style="text-align:center;">
0.33
</td>
<td style="text-align:center;">
0.11
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
2.38
</td>
<td style="text-align:right;">
.068
</td>
<td style="text-align:right;">
.787
</td>
</tr>
<tr>
<td style="text-align:left;">
nervous
</td>
<td style="text-align:center;">
Y
</td>
<td style="text-align:center;">
0.29
</td>
<td style="text-align:center;">
0.10
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
1.70
</td>
<td style="text-align:right;">
.165
</td>
<td style="text-align:right;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
reckless
</td>
<td style="text-align:center;">
Y
</td>
<td style="text-align:center;">
1.55
</td>
<td style="text-align:center;">
0.52
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
8.03
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
.001
</td>
</tr>
<tr>
<td style="text-align:left;">
worrying
</td>
<td style="text-align:center;">
Y
</td>
<td style="text-align:center;">
1.13
</td>
<td style="text-align:center;">
0.38
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
970
</td>
<td style="text-align:center;">
8.25
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
.001
</td>
</tr>
</tbody>
</table>
</div>
<div id="pairwise-t-tests-for-significant-anovas-1"
class="section level3">
<h3>Pairwise t-tests for significant ANOVAs</h3>
<p>When format was a significant predictor of extreme responding for an
item (using the un-adjusted <em>p</em>-value here), we follow up with
pairwise comparisons of format. Here we identify the items which meet
this criteria. In the manuscript proper, we will only report the results
for items in which format was significant, even after applying the Holm
correction.</p>
<pre class="r"><code>sig_item_ex = summary_by_item_ex %&gt;%
  filter(p.value &lt; .05)

sig_item_ex = sig_item_ex$item
sig_item_ex</code></pre>
<pre><code>##  [1] &quot;helpful&quot;     &quot;reckless&quot;    &quot;friendly&quot;    &quot;warm&quot;        &quot;worrying&quot;   
##  [6] &quot;caring&quot;      &quot;creative&quot;    &quot;hardworking&quot; &quot;imaginative&quot; &quot;intelligent&quot;
## [11] &quot;curious&quot;     &quot;active&quot;      &quot;careless&quot;    &quot;broadminded&quot; &quot;impulsive&quot;  
## [16] &quot;sympathetic&quot; &quot;talkative&quot;   &quot;adventurous&quot;</code></pre>
<p>Then we create models for each adjective. We use the
<code>emmeans</code> package to perform pairwise comparisons, again with
a Holm correction on the <em>p</em>-values. We also plot the means and
95% confidence intervals of each mean. Likelihood differences are shown
in Table @ref(tab:responsestyle23) and likelihood estimates are in
Figure @ref(fig:responsestyle24).</p>
<pre class="r"><code>pairwise_response_ex = mod_by_item_ex %&gt;% 
  #only significant items
  filter(item %in% sig_item_ex) %&gt;% 
  #use emmeans package to calculate format means and run pairwise comparisons
  mutate(comp = map(mod, emmeans, pairwise~format, adjust = &quot;none&quot;),
         means = map(comp, &quot;emmeans&quot;),
         means = map(means, as.data.frame),
         contrasts = map(comp, &quot;contrasts&quot;),
         contrasts = map(contrasts, as.data.frame))</code></pre>
<pre class="r"><code>pairwise_response_ex %&gt;% 
  select(item, contrasts) %&gt;% 
  unnest(cols = c(contrasts)) %&gt;% 
  mutate(estimate = printnum(estimate),
         estimate = case_when(
           p.value &lt; .001 ~ paste0(estimate, &quot;***&quot;),
           p.value &lt; .01 ~ paste0(estimate, &quot;**&quot;),
           p.value &lt; .05 ~ paste0(estimate, &quot;*&quot;),
           TRUE ~ estimate
         )) %&gt;% 
  mutate(
    contrast = str_replace(contrast, &quot;Adjective\nOnly&quot;, &quot;A&quot;),
    contrast = str_replace(contrast, &quot;Am\nAdjective&quot;, &quot;B&quot;),
    contrast = str_replace(contrast, &quot;Tend to be\nAdjective&quot;, &quot;C&quot;),
    contrast = str_replace(contrast, &quot;Am someone\nwho tends to be\nAdjective&quot;, &quot;D&quot;),
    contrast = str_remove_all(contrast, &quot; &quot;)
  ) %&gt;% 
  select(item, contrast, estimate) %&gt;% 
  pivot_wider(names_from = contrast, values_from = estimate) %&gt;% 
  kable(booktabs = T,
        caption = &quot;Pairwise differences in likelihood of extreme responding by format. A = Adjective only. B = Am Adjective. C = Tend to be Adjective. D = Am someone who tends to be Adjective. * p &lt; .05, ** p &lt; .01, *** p &lt; .001&quot;) %&gt;%
  kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
Pairwise differences in likelihood of extreme responding by format. A =
Adjective only. B = Am Adjective. C = Tend to be Adjective. D = Am
someone who tends to be Adjective. * p
</caption>
<thead>
<tr>
<th style="text-align:left;">
item
</th>
<th style="text-align:left;">
A-B
</th>
<th style="text-align:left;">
A-C
</th>
<th style="text-align:left;">
A-D
</th>
<th style="text-align:left;">
B-C
</th>
<th style="text-align:left;">
B-D
</th>
<th style="text-align:left;">
C-D
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
helpful
</td>
<td style="text-align:left;">
-0.67
</td>
<td style="text-align:left;">
-0.60
</td>
<td style="text-align:left;">
-0.62
</td>
<td style="text-align:left;">
0.07
</td>
<td style="text-align:left;">
0.05
</td>
<td style="text-align:left;">
-0.02
</td>
</tr>
<tr>
<td style="text-align:left;">
reckless
</td>
<td style="text-align:left;">
-0.45
</td>
<td style="text-align:left;">
0.12
</td>
<td style="text-align:left;">
-0.79*
</td>
<td style="text-align:left;">
0.56
</td>
<td style="text-align:left;">
-0.34
</td>
<td style="text-align:left;">
-0.90*
</td>
</tr>
<tr>
<td style="text-align:left;">
friendly
</td>
<td style="text-align:left;">
0.38
</td>
<td style="text-align:left;">
0.01
</td>
<td style="text-align:left;">
-0.23
</td>
<td style="text-align:left;">
-0.36
</td>
<td style="text-align:left;">
-0.60
</td>
<td style="text-align:left;">
-0.24
</td>
</tr>
<tr>
<td style="text-align:left;">
warm
</td>
<td style="text-align:left;">
-0.34
</td>
<td style="text-align:left;">
0.12
</td>
<td style="text-align:left;">
0.63
</td>
<td style="text-align:left;">
0.47
</td>
<td style="text-align:left;">
0.97
</td>
<td style="text-align:left;">
0.51
</td>
</tr>
<tr>
<td style="text-align:left;">
worrying
</td>
<td style="text-align:left;">
-0.59
</td>
<td style="text-align:left;">
-0.44
</td>
<td style="text-align:left;">
-0.54
</td>
<td style="text-align:left;">
0.15
</td>
<td style="text-align:left;">
0.05
</td>
<td style="text-align:left;">
-0.09
</td>
</tr>
<tr>
<td style="text-align:left;">
caring
</td>
<td style="text-align:left;">
-0.52
</td>
<td style="text-align:left;">
-0.49
</td>
<td style="text-align:left;">
-0.91*
</td>
<td style="text-align:left;">
0.03
</td>
<td style="text-align:left;">
-0.38
</td>
<td style="text-align:left;">
-0.41
</td>
</tr>
<tr>
<td style="text-align:left;">
creative
</td>
<td style="text-align:left;">
-0.98*
</td>
<td style="text-align:left;">
-0.09
</td>
<td style="text-align:left;">
-0.65
</td>
<td style="text-align:left;">
0.89
</td>
<td style="text-align:left;">
0.33
</td>
<td style="text-align:left;">
-0.56
</td>
</tr>
<tr>
<td style="text-align:left;">
hardworking
</td>
<td style="text-align:left;">
0.13
</td>
<td style="text-align:left;">
0.27
</td>
<td style="text-align:left;">
0.01
</td>
<td style="text-align:left;">
0.13
</td>
<td style="text-align:left;">
-0.12
</td>
<td style="text-align:left;">
-0.26
</td>
</tr>
<tr>
<td style="text-align:left;">
imaginative
</td>
<td style="text-align:left;">
0.26
</td>
<td style="text-align:left;">
-0.04
</td>
<td style="text-align:left;">
-0.19
</td>
<td style="text-align:left;">
-0.30
</td>
<td style="text-align:left;">
-0.45
</td>
<td style="text-align:left;">
-0.15
</td>
</tr>
<tr>
<td style="text-align:left;">
intelligent
</td>
<td style="text-align:left;">
0.30
</td>
<td style="text-align:left;">
0.02
</td>
<td style="text-align:left;">
-0.11
</td>
<td style="text-align:left;">
-0.27
</td>
<td style="text-align:left;">
-0.41
</td>
<td style="text-align:left;">
-0.14
</td>
</tr>
<tr>
<td style="text-align:left;">
curious
</td>
<td style="text-align:left;">
-0.68
</td>
<td style="text-align:left;">
-0.23
</td>
<td style="text-align:left;">
-0.62
</td>
<td style="text-align:left;">
0.45
</td>
<td style="text-align:left;">
0.06
</td>
<td style="text-align:left;">
-0.39
</td>
</tr>
<tr>
<td style="text-align:left;">
active
</td>
<td style="text-align:left;">
-0.27
</td>
<td style="text-align:left;">
0.06
</td>
<td style="text-align:left;">
-0.93
</td>
<td style="text-align:left;">
0.33
</td>
<td style="text-align:left;">
-0.66
</td>
<td style="text-align:left;">
-0.99
</td>
</tr>
<tr>
<td style="text-align:left;">
careless
</td>
<td style="text-align:left;">
-0.28
</td>
<td style="text-align:left;">
-0.55
</td>
<td style="text-align:left;">
-0.61
</td>
<td style="text-align:left;">
-0.28
</td>
<td style="text-align:left;">
-0.34
</td>
<td style="text-align:left;">
-0.06
</td>
</tr>
<tr>
<td style="text-align:left;">
broadminded
</td>
<td style="text-align:left;">
-0.96*
</td>
<td style="text-align:left;">
-0.52
</td>
<td style="text-align:left;">
-0.29
</td>
<td style="text-align:left;">
0.45
</td>
<td style="text-align:left;">
0.67
</td>
<td style="text-align:left;">
0.23
</td>
</tr>
<tr>
<td style="text-align:left;">
impulsive
</td>
<td style="text-align:left;">
-0.77
</td>
<td style="text-align:left;">
-0.71
</td>
<td style="text-align:left;">
-1.57**
</td>
<td style="text-align:left;">
0.06
</td>
<td style="text-align:left;">
-0.79
</td>
<td style="text-align:left;">
-0.86
</td>
</tr>
<tr>
<td style="text-align:left;">
sympathetic
</td>
<td style="text-align:left;">
-0.79
</td>
<td style="text-align:left;">
-0.73
</td>
<td style="text-align:left;">
-0.76
</td>
<td style="text-align:left;">
0.07
</td>
<td style="text-align:left;">
0.04
</td>
<td style="text-align:left;">
-0.03
</td>
</tr>
<tr>
<td style="text-align:left;">
talkative
</td>
<td style="text-align:left;">
0.49
</td>
<td style="text-align:left;">
-0.38
</td>
<td style="text-align:left;">
-0.75
</td>
<td style="text-align:left;">
-0.87
</td>
<td style="text-align:left;">
-1.24**
</td>
<td style="text-align:left;">
-0.37
</td>
</tr>
<tr>
<td style="text-align:left;">
adventurous
</td>
<td style="text-align:left;">
-0.88
</td>
<td style="text-align:left;">
-0.44
</td>
<td style="text-align:left;">
-1.83**
</td>
<td style="text-align:left;">
0.44
</td>
<td style="text-align:left;">
-0.96
</td>
<td style="text-align:left;">
-1.40**
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>logit2prob &lt;- function(logit){
  odds &lt;- exp(logit)
  prob &lt;- odds / (1 + odds)
  return(prob)
}

pairwise_response_ex %&gt;% 
  select(item, means) %&gt;% 
  unnest(cols = c(means)) %&gt;% 
  mutate(format = case_when(
    format == &quot;Adjective\nOnly&quot; ~ 1,
    format == &quot;Am\nAdjective&quot; ~ 2,
    format == &quot;Tend to be\nAdjective&quot; ~ 3,
    format == &quot;Am someone\nwho tends to be\nAdjective&quot; ~ 4)) %&gt;% 
  mutate(across(c(emmean, lower.CL, upper.CL), logit2prob)) %&gt;% 
  ggplot(aes(x = format, y = emmean)) +
  geom_point(stat = &quot;identity&quot;) + 
  geom_line(alpha = .3) +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = .3) +
  scale_x_continuous(breaks = c(1:4), labels= c(&quot;A&quot;,&quot;B&quot;,&quot;C&quot;,&quot;D&quot;)) +
  labs(x = NULL, y = &quot;Probability of extreme response&quot;) +
  facet_wrap(~item) +
  theme_pubr() </code></pre>
<div class="figure">
<img src="response_style_files/figure-html/responsestyle24-1.png" alt="Extreme responding by format and item. These items were significantly affected by response. A = Adjective only. B = Am Adjective. C = Tend to be Adjective. D = Am someone who tends to be Adjective." width="672" />
<p class="caption">
Extreme responding by format and item. These items were significantly
affected by response. A = Adjective only. B = Am Adjective. C = Tend to
be Adjective. D = Am someone who tends to be Adjective.
</p>
</div>
</div>
</div>
<div id="yea-saying" class="section level2">
<h2>Yea-saying</h2>
<p>We define <em>yea-saying</em> as answering “somewhat accurate” (4),
“accurate” (5), or “very accurate” (6) to an item. To model likelihood
of extreme responding by format, we use logistic regression. As a
reminder, we reverse-scored socially desirable items during the cleaning
stage. For those items, responses coded as 1, 2, or 3 represent
agreement (accurate). Therefore, we code values 1, 2, and 3 as
yea-saying for reverse-scored items, and values 4, 5, and 6 as
yea-saying for all other items.</p>
<p>For these analyses, we only used a set of matched pairs of adjectives
to create balanced subsets of positively and negatively keyed items.</p>
<pre class="r"><code>items_df = items_df %&gt;% 
  mutate(
    yeasaying = case_when(
    item %in% reverse &amp; response %in% c(1:3) ~ 1,
    !(item %in% reverse) &amp; response %in% c(4:6) ~ 1,
    TRUE ~ 0
  ))</code></pre>
<pre class="r"><code>mod.yeasaying = items_df %&gt;% 
  filter(block %in% c(1,2)) %&gt;%
  filter(item %in% 
           c(&quot;outgoing&quot;, &quot;shy&quot;, &quot;talkative&quot;, &quot;quiet&quot;,
             &quot;sympathetic&quot;, &quot;unsympathetic&quot;, &quot;warm&quot;, &quot;cold&quot;,
             &quot;cautious&quot;, &quot;careless&quot;, &quot;responsible&quot;, &quot;reckless&quot;,
             &quot;worrying&quot;, &quot;relaxed&quot;, &quot;nervous&quot;, &quot;calm&quot;,
             &quot;creative&quot;, &quot;uncreative&quot;, &quot;intelligent&quot;, &quot;unintellectual&quot;)) %&gt;% 
  glmmTMB(yeasaying~format + (1|proid) + (1|item) + (1|block), 
                  data = ., 
                  family = &quot;binomial&quot;)
tidy(aov(mod.yeasaying))</code></pre>
<pre><code>## # A tibble: 5 × 6
##   term         df     sumsq   meansq statistic    p.value
##   &lt;chr&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
## 1 format        3    0.838    0.279      1.92   1.24e-  1
## 2 proid       973  551.       0.567      3.89   1.52e-305
## 3 item         19 2435.     128.       880.     0        
## 4 block         1    0.0538   0.0538     0.369  5.44e-  1
## 5 Residuals 37963 5530.       0.146     NA     NA</code></pre>
<p>Item format was unassociated with participants’ expected responses to
personality items <span class="math inline">\((F(3.00, 37,963.00) =
1.92, p = .124)\)</span>. See Figure @ref(fig:responsestyle28) for a
visualization of this effect.</p>
<div class="figure">
<img src="response_style_files/figure-html/responsestyle28-1.png" alt="Predicted response on personality items by condition." width="672" />
<p class="caption">
Predicted response on personality items by condition.
</p>
</div>
<div id="one-model-for-each-adjective-2" class="section level3">
<h3>One model for each adjective</h3>
<p>We repeat this analysis separately for each trait.</p>
<pre class="r"><code>mod_by_item_ya = items_df %&gt;%
  filter(item %in% 
           c(&quot;outgoing&quot;, &quot;shy&quot;, &quot;talkative&quot;, &quot;quiet&quot;,
             &quot;sympathetic&quot;, &quot;unsympathetic&quot;, &quot;warm&quot;, &quot;cold&quot;,
             &quot;cautious&quot;, &quot;careless&quot;, &quot;responsible&quot;, &quot;reckless&quot;,
             &quot;worrying&quot;, &quot;relaxed&quot;, &quot;nervous&quot;, &quot;calm&quot;,
             &quot;creative&quot;, &quot;uncreative&quot;, &quot;intelligent&quot;, &quot;unintellectual&quot;)) %&gt;% 
  group_by(item) %&gt;%
  nest() %&gt;%
  mutate(mod = map(data, ~glmmTMB(yeasaying~format + (1|proid) + (1|block), 
                                  data = .,
                                  family = &quot;binomial&quot;))) %&gt;%
  mutate(aov = map(mod, aov))</code></pre>
<p>We apply a Holm correction to the <em>p</em>-values extracted from
these analyses, to adjust for the number of tests conducted. We present
results in Table @ref(tab:responsestyle30), which is organized by
whether items were reverse-coded prior to analysis.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
Format effects on yea-saying by item.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Item
</th>
<th style="text-align:center;">
Reverse Scored?
</th>
<th style="text-align:center;">
SS
</th>
<th style="text-align:center;">
MS
</th>
<th style="text-align:center;">
df
</th>
<th style="text-align:center;">
df2
</th>
<th style="text-align:center;">
F
</th>
<th style="text-align:right;">
raw
</th>
<th style="text-align:right;">
adj
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
calm
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.74
</td>
<td style="text-align:center;">
0.25
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1852
</td>
<td style="text-align:center;">
5.02
</td>
<td style="text-align:right;">
.002
</td>
<td style="text-align:right;">
.018
</td>
</tr>
<tr>
<td style="text-align:left;">
cautious
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.21
</td>
<td style="text-align:center;">
0.07
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1852
</td>
<td style="text-align:center;">
1.36
</td>
<td style="text-align:right;">
.253
</td>
<td style="text-align:right;">
.758
</td>
</tr>
<tr>
<td style="text-align:left;">
cold
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
1.43
</td>
<td style="text-align:center;">
0.48
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1852
</td>
<td style="text-align:center;">
7.69
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
.001
</td>
</tr>
<tr>
<td style="text-align:left;">
creative
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.07
</td>
<td style="text-align:center;">
0.02
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1852
</td>
<td style="text-align:center;">
0.65
</td>
<td style="text-align:right;">
.585
</td>
<td style="text-align:right;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
intelligent
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.10
</td>
<td style="text-align:center;">
0.03
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1852
</td>
<td style="text-align:center;">
2.05
</td>
<td style="text-align:right;">
.105
</td>
<td style="text-align:right;">
.451
</td>
</tr>
<tr>
<td style="text-align:left;">
outgoing
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
2.58
</td>
<td style="text-align:center;">
0.86
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1852
</td>
<td style="text-align:center;">
14.76
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
&lt; .001
</td>
</tr>
<tr>
<td style="text-align:left;">
quiet
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.13
</td>
<td style="text-align:center;">
0.04
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1852
</td>
<td style="text-align:center;">
0.77
</td>
<td style="text-align:right;">
.512
</td>
<td style="text-align:right;">
&gt; .999
</td>
</tr>
<tr>
<td style="text-align:left;">
relaxed
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
1.27
</td>
<td style="text-align:center;">
0.42
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1852
</td>
<td style="text-align:center;">
6.60
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
.003
</td>
</tr>
<tr>
<td style="text-align:left;">
responsible
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.42
</td>
<td style="text-align:center;">
0.14
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1852
</td>
<td style="text-align:center;">
4.49
</td>
<td style="text-align:right;">
.004
</td>
<td style="text-align:right;">
.034
</td>
</tr>
<tr>
<td style="text-align:left;">
shy
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
1.83
</td>
<td style="text-align:center;">
0.61
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1852
</td>
<td style="text-align:center;">
10.51
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
&lt; .001
</td>
</tr>
<tr>
<td style="text-align:left;">
sympathetic
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.51
</td>
<td style="text-align:center;">
0.17
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1852
</td>
<td style="text-align:center;">
6.25
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
.004
</td>
</tr>
<tr>
<td style="text-align:left;">
talkative
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.55
</td>
<td style="text-align:center;">
0.18
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1852
</td>
<td style="text-align:center;">
2.48
</td>
<td style="text-align:right;">
.059
</td>
<td style="text-align:right;">
.355
</td>
</tr>
<tr>
<td style="text-align:left;">
uncreative
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.42
</td>
<td style="text-align:center;">
0.14
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1852
</td>
<td style="text-align:center;">
2.62
</td>
<td style="text-align:right;">
.049
</td>
<td style="text-align:right;">
.344
</td>
</tr>
<tr>
<td style="text-align:left;">
unintellectual
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.26
</td>
<td style="text-align:center;">
0.09
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1852
</td>
<td style="text-align:center;">
2.17
</td>
<td style="text-align:right;">
.090
</td>
<td style="text-align:right;">
.451
</td>
</tr>
<tr>
<td style="text-align:left;">
unsympathetic
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
1.23
</td>
<td style="text-align:center;">
0.41
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1852
</td>
<td style="text-align:center;">
7.50
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
.001
</td>
</tr>
<tr>
<td style="text-align:left;">
warm
</td>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
0.56
</td>
<td style="text-align:center;">
0.19
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1852
</td>
<td style="text-align:center;">
5.11
</td>
<td style="text-align:right;">
.002
</td>
<td style="text-align:right;">
.018
</td>
</tr>
<tr>
<td style="text-align:left;">
careless
</td>
<td style="text-align:center;">
Y
</td>
<td style="text-align:center;">
0.79
</td>
<td style="text-align:center;">
0.26
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1852
</td>
<td style="text-align:center;">
3.60
</td>
<td style="text-align:right;">
.013
</td>
<td style="text-align:right;">
.104
</td>
</tr>
<tr>
<td style="text-align:left;">
nervous
</td>
<td style="text-align:center;">
Y
</td>
<td style="text-align:center;">
1.13
</td>
<td style="text-align:center;">
0.38
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1852
</td>
<td style="text-align:center;">
6.24
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
.004
</td>
</tr>
<tr>
<td style="text-align:left;">
reckless
</td>
<td style="text-align:center;">
Y
</td>
<td style="text-align:center;">
2.21
</td>
<td style="text-align:center;">
0.74
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1852
</td>
<td style="text-align:center;">
14.23
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
&lt; .001
</td>
</tr>
<tr>
<td style="text-align:left;">
worrying
</td>
<td style="text-align:center;">
Y
</td>
<td style="text-align:center;">
1.21
</td>
<td style="text-align:center;">
0.40
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1852
</td>
<td style="text-align:center;">
6.35
</td>
<td style="text-align:right;">
&lt; .001
</td>
<td style="text-align:right;">
.004
</td>
</tr>
</tbody>
</table>
</div>
<div id="pairwise-t-tests-for-significant-anovas-2"
class="section level3">
<h3>Pairwise t-tests for significant ANOVAs</h3>
<p>When format was a significant predictor of extreme responding for an
item (using the un-adjusted <em>p</em>-value here), we follow up with
pairwise comparisons of format. Here we identify the items which meet
this criteria. In the manuscript proper, we will only report the results
for items in which format was significant, even after applying the Holm
correction.</p>
<pre class="r"><code>sig_item_ya = summary_by_item_ya %&gt;%
  filter(p.value &lt; .05)

sig_item_ya = sig_item_ya$item
sig_item_ya</code></pre>
<pre><code>##  [1] &quot;outgoing&quot;      &quot;reckless&quot;      &quot;warm&quot;          &quot;worrying&quot;     
##  [5] &quot;responsible&quot;   &quot;nervous&quot;       &quot;calm&quot;          &quot;careless&quot;     
##  [9] &quot;sympathetic&quot;   &quot;unsympathetic&quot; &quot;relaxed&quot;       &quot;uncreative&quot;   
## [13] &quot;shy&quot;           &quot;cold&quot;</code></pre>
<p>Then we create models for each adjective. We use the
<code>emmeans</code> package to perform pairwise comparisons, again with
a Holm correction on the <em>p</em>-values. We also plot the means and
95% confidence intervals of each mean. Likelihood differences are shown
in Table @ref(tab:responsestyle23) and likelihood estimates are in
Figure @ref(fig:responsestyle24).</p>
<pre class="r"><code>pairwise_response_ya = mod_by_item_ya %&gt;% 
  #only significant items
  filter(item %in% sig_item_ya) %&gt;% 
  #use emmeans package to calculate format means and run pairwise comparisons
  mutate(comp = map(mod, emmeans, pairwise~format, adjust = &quot;none&quot;),
         means = map(comp, &quot;emmeans&quot;),
         means = map(means, as.data.frame),
         contrasts = map(comp, &quot;contrasts&quot;),
         contrasts = map(contrasts, as.data.frame))</code></pre>
<pre class="r"><code>pairwise_response_ya %&gt;% 
  select(item, contrasts) %&gt;% 
  unnest(cols = c(contrasts)) %&gt;% 
  mutate(estimate = printnum(estimate),
         estimate = case_when(
           p.value &lt; .001 ~ paste0(estimate, &quot;***&quot;),
           p.value &lt; .01 ~ paste0(estimate, &quot;**&quot;),
           p.value &lt; .05 ~ paste0(estimate, &quot;*&quot;),
           TRUE ~ estimate
         )) %&gt;% 
  mutate(
    contrast = str_replace(contrast, &quot;Adjective\nOnly&quot;, &quot;A&quot;),
    contrast = str_replace(contrast, &quot;Am\nAdjective&quot;, &quot;B&quot;),
    contrast = str_replace(contrast, &quot;Tend to be\nAdjective&quot;, &quot;C&quot;),
    contrast = str_replace(contrast, &quot;Am someone\nwho tends to be\nAdjective&quot;, &quot;D&quot;),
    contrast = str_remove_all(contrast, &quot; &quot;)
  ) %&gt;% 
  select(item, contrast, estimate) %&gt;% 
  pivot_wider(names_from = contrast, values_from = estimate) %&gt;% 
  kable(booktabs = T,
        caption = &quot;Pairwise differences in likelihood of yea-saying by format. A = Adjective only. B = Am Adjective. C = Tend to be Adjective. D = Am someone who tends to be Adjective. * p &lt; .05, ** p &lt; .01, *** p &lt; .001&quot;) %&gt;%
  kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
Pairwise differences in likelihood of yea-saying by format. A =
Adjective only. B = Am Adjective. C = Tend to be Adjective. D = Am
someone who tends to be Adjective. * p
</caption>
<thead>
<tr>
<th style="text-align:left;">
item
</th>
<th style="text-align:left;">
A-B
</th>
<th style="text-align:left;">
A-C
</th>
<th style="text-align:left;">
A-D
</th>
<th style="text-align:left;">
B-C
</th>
<th style="text-align:left;">
B-D
</th>
<th style="text-align:left;">
C-D
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
outgoing
</td>
<td style="text-align:left;">
-0.04
</td>
<td style="text-align:left;">
0.42
</td>
<td style="text-align:left;">
0.52
</td>
<td style="text-align:left;">
0.47
</td>
<td style="text-align:left;">
0.57*
</td>
<td style="text-align:left;">
0.10
</td>
</tr>
<tr>
<td style="text-align:left;">
reckless
</td>
<td style="text-align:left;">
-0.73
</td>
<td style="text-align:left;">
-0.57
</td>
<td style="text-align:left;">
-0.69
</td>
<td style="text-align:left;">
0.16
</td>
<td style="text-align:left;">
0.03
</td>
<td style="text-align:left;">
-0.13
</td>
</tr>
<tr>
<td style="text-align:left;">
warm
</td>
<td style="text-align:left;">
0.55
</td>
<td style="text-align:left;">
0.65
</td>
<td style="text-align:left;">
0.24
</td>
<td style="text-align:left;">
0.10
</td>
<td style="text-align:left;">
-0.32
</td>
<td style="text-align:left;">
-0.41
</td>
</tr>
<tr>
<td style="text-align:left;">
worrying
</td>
<td style="text-align:left;">
0.52
</td>
<td style="text-align:left;">
-0.03
</td>
<td style="text-align:left;">
-0.04
</td>
<td style="text-align:left;">
-0.55
</td>
<td style="text-align:left;">
-0.57
</td>
<td style="text-align:left;">
-0.01
</td>
</tr>
<tr>
<td style="text-align:left;">
responsible
</td>
<td style="text-align:left;">
1.04
</td>
<td style="text-align:left;">
0.58
</td>
<td style="text-align:left;">
1.65**
</td>
<td style="text-align:left;">
-0.47
</td>
<td style="text-align:left;">
0.61
</td>
<td style="text-align:left;">
1.07*
</td>
</tr>
<tr>
<td style="text-align:left;">
nervous
</td>
<td style="text-align:left;">
0.02
</td>
<td style="text-align:left;">
-0.36
</td>
<td style="text-align:left;">
-0.36
</td>
<td style="text-align:left;">
-0.38
</td>
<td style="text-align:left;">
-0.38
</td>
<td style="text-align:left;">
0.01
</td>
</tr>
<tr>
<td style="text-align:left;">
calm
</td>
<td style="text-align:left;">
0.25
</td>
<td style="text-align:left;">
0.57
</td>
<td style="text-align:left;">
0.85*
</td>
<td style="text-align:left;">
0.32
</td>
<td style="text-align:left;">
0.60
</td>
<td style="text-align:left;">
0.28
</td>
</tr>
<tr>
<td style="text-align:left;">
careless
</td>
<td style="text-align:left;">
-0.15
</td>
<td style="text-align:left;">
-0.21
</td>
<td style="text-align:left;">
-0.17
</td>
<td style="text-align:left;">
-0.06
</td>
<td style="text-align:left;">
-0.02
</td>
<td style="text-align:left;">
0.04
</td>
</tr>
<tr>
<td style="text-align:left;">
sympathetic
</td>
<td style="text-align:left;">
1.01
</td>
<td style="text-align:left;">
1.05
</td>
<td style="text-align:left;">
0.07
</td>
<td style="text-align:left;">
0.04
</td>
<td style="text-align:left;">
-0.94
</td>
<td style="text-align:left;">
-0.98
</td>
</tr>
<tr>
<td style="text-align:left;">
unsympathetic
</td>
<td style="text-align:left;">
-0.53
</td>
<td style="text-align:left;">
0.42
</td>
<td style="text-align:left;">
0.13
</td>
<td style="text-align:left;">
0.95**
</td>
<td style="text-align:left;">
0.65
</td>
<td style="text-align:left;">
-0.30
</td>
</tr>
<tr>
<td style="text-align:left;">
relaxed
</td>
<td style="text-align:left;">
-0.74*
</td>
<td style="text-align:left;">
0.10
</td>
<td style="text-align:left;">
0.25
</td>
<td style="text-align:left;">
0.83*
</td>
<td style="text-align:left;">
0.99**
</td>
<td style="text-align:left;">
0.15
</td>
</tr>
<tr>
<td style="text-align:left;">
uncreative
</td>
<td style="text-align:left;">
-0.07
</td>
<td style="text-align:left;">
0.55
</td>
<td style="text-align:left;">
0.65
</td>
<td style="text-align:left;">
0.61
</td>
<td style="text-align:left;">
0.72
</td>
<td style="text-align:left;">
0.11
</td>
</tr>
<tr>
<td style="text-align:left;">
shy
</td>
<td style="text-align:left;">
-0.01
</td>
<td style="text-align:left;">
0.72*
</td>
<td style="text-align:left;">
0.02
</td>
<td style="text-align:left;">
0.73*
</td>
<td style="text-align:left;">
0.03
</td>
<td style="text-align:left;">
-0.70*
</td>
</tr>
<tr>
<td style="text-align:left;">
cold
</td>
<td style="text-align:left;">
0.73*
</td>
<td style="text-align:left;">
0.66
</td>
<td style="text-align:left;">
0.33
</td>
<td style="text-align:left;">
-0.07
</td>
<td style="text-align:left;">
-0.40
</td>
<td style="text-align:left;">
-0.33
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>pairwise_response_ya %&gt;% 
  select(item, means) %&gt;% 
  unnest(cols = c(means)) %&gt;% 
  mutate(format = case_when(
    format == &quot;Adjective\nOnly&quot; ~ 1,
    format == &quot;Am\nAdjective&quot; ~ 2,
    format == &quot;Tend to be\nAdjective&quot; ~ 3,
    format == &quot;Am someone\nwho tends to be\nAdjective&quot; ~ 4)) %&gt;% 
  mutate(across(c(emmean, lower.CL, upper.CL), logit2prob)) %&gt;% 
  ggplot(aes(x = format, y = emmean)) +
  geom_point(stat = &quot;identity&quot;) + 
  geom_line(alpha = .3) +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = .3) +
  scale_x_continuous(breaks = c(1:4), labels= c(&quot;A&quot;,&quot;B&quot;,&quot;C&quot;,&quot;D&quot;)) +
  labs(x = NULL, y = &quot;Probability of yeasaying&quot;) +
  facet_wrap(~item) +
  theme_pubr() </code></pre>
<div class="figure">
<img src="response_style_files/figure-html/responsestyle33-1.png" alt="Yea-saying by format and item. These items were significantly affected by response. A = Adjective only. B = Am Adjective. C = Tend to be Adjective. D = Am someone who tends to be Adjective." width="672" />
<p class="caption">
Yea-saying by format and item. These items were significantly affected
by response. A = Adjective only. B = Am Adjective. C = Tend to be
Adjective. D = Am someone who tends to be Adjective.
</p>
</div>
</div>
</div>
<div id="all-tests" class="section level2">
<h2>All tests</h2>
<p><img src="response_style_files/figure-html/unnamed-chunk-6-1.png" width="480" /></p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
