---
title: "Workspace Information"
date: "Last updated `r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---


```{r workspace-1, include = FALSE}
knitr::opts_chunk$set(warning = F, message = F)
```

```{r workspace-2, echo = F}
library(here)
library(knitr) #tables
library(kableExtra) # for nicer tables
library(tidyverse)
```



```{r workspace-3, echo = F, results = 'asis'}
wkspc = sessionInfo()
```

All data cleaning and analyses were completed using `r wkspc$R.version$version.string` (`r wkspc$R.version$nickname`). Below we list the packages (and versions) used in these analyses. 

```{r workspace-4, echo = F, results = 'asis'}
packages = wkspc$otherPkgs
package.df = tibble(package = names(packages))
package.df$list = packages
package.df2 = package.df
load(here("objects/packagedf.Rds"))
if(nrow(package.df2) > nrow(package.df)){
  package.df = package.df2
  save(package.df, file = here("objects/packagedf.Rds"))
}


package.df %>% 
  mutate(version = map_chr(list, "Version"),
         author = map_chr(list, "Author")) %>% 
  select(-list) %>% 
  kable(booktabs = T, longtable = T,
        col.names = c("Package", "Version", "Authors and contributors")) %>% 
  kable_styling(latex_options = c("repeat_header")) %>% 
  column_spec(3, width = "5in")
```


